// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib = require("@rescript/runtime/lib/js/Stdlib.js");
let Nodefs = require("node:fs");
let Nodeos = require("node:os");
let Process = require("process");
let Buntest = require("bun:test");
let Nodepath = require("node:path");

let NodeFs = {};

let modulePath = Nodepath.join(Process.cwd(), "res-x-vite-plugin.mjs");

let helpers = require(modulePath).__test;

let PluginTestHelpers = {
  modulePath: modulePath,
  helpers: helpers
};

let defaultClientEntryExtensions = [
  ".js",
  ".mjs",
  ".jsx",
  ".ts",
  ".tsx"
];

let defaultEntryGlobs = defaultClientEntryExtensions.map(extension => "*" + extension);

async function withTempDir(run) {
  let tempDir = Nodefs.mkdtempSync(Nodepath.join(Nodeos.tmpdir(), "resx-asset-map-"));
  try {
    let result = await run(tempDir);
    Nodefs.rmSync(tempDir, {
      recursive: true,
      force: true
    });
    return result;
  } catch (exn) {
    Nodefs.rmSync(tempDir, {
      recursive: true,
      force: true
    });
    throw exn;
  }
}

function getManifestOptions(projectRoot, extraClientEntriesOpt) {
  let extraClientEntries = extraClientEntriesOpt !== undefined ? extraClientEntriesOpt : ({});
  return {
    assetDir: "assets",
    assetEntryGlobs: defaultEntryGlobs,
    clientDirs: [],
    clientEntryExtensions: defaultClientEntryExtensions,
    clientEntryGlobs: defaultEntryGlobs,
    extraClientEntries: extraClientEntries,
    projectRoot: projectRoot
  };
}

function getManifestEntry(manifest, fieldName) {
  let entry = manifest.find(entry => entry.fieldName === fieldName);
  if (entry !== undefined) {
    return entry;
  } else {
    return Stdlib.panic(`Missing manifest entry for ` + fieldName);
  }
}

function expectContains(text, substring) {
  Buntest.expect(text.includes(substring)).toBe(true);
}

Buntest.describe("asset map generation", () => {
  Buntest.test("uses @as for keyword asset names while preserving runtime keys", async () => await withTempDir(async tempDir => {
    Nodefs.mkdirSync(Nodepath.join(tempDir, "assets"), {
      recursive: true
    });
    Nodefs.writeFileSync(Nodepath.join(tempDir, "assets", "type"), "type asset");
    let manifest = helpers.getManifest(getManifestOptions(tempDir, undefined));
    let typeEntry = getManifestEntry(manifest, "type");
    Buntest.expect(typeEntry.rescriptFieldName).toBe("type_");
    let resTypeFile = helpers.getResTypeFileContent(manifest);
    expectContains(resTypeFile, `@as("type")`);
    expectContains(resTypeFile, "type_: string");
    let devAssetMap = helpers.getGeneratedDevAssetMap(manifest);
    return expectContains(devAssetMap, `"type": "/assets/type"`);
  }));
  Buntest.test("keeps existing safe field labels when keyword aliases would collide", async () => await withTempDir(async tempDir => {
    Nodefs.mkdirSync(Nodepath.join(tempDir, "assets"), {
      recursive: true
    });
    Nodefs.writeFileSync(Nodepath.join(tempDir, "assets", "type"), "type asset");
    Nodefs.writeFileSync(Nodepath.join(tempDir, "assets", "type_"), "type_ asset");
    let manifest = helpers.getManifest(getManifestOptions(tempDir, undefined));
    let typeEntry = getManifestEntry(manifest, "type");
    let typeUnderscoreEntry = getManifestEntry(manifest, "type_");
    Buntest.expect(typeEntry.rescriptFieldName).toBe("type__");
    Buntest.expect(typeUnderscoreEntry.rescriptFieldName).toBe("type_");
    let resTypeFile = helpers.getResTypeFileContent(manifest);
    expectContains(resTypeFile, `@as("type")`);
    expectContains(resTypeFile, "type__: string");
    return expectContains(resTypeFile, "type_: string");
  }));
  Buntest.test("uses @as for keyword extra client entry names", async () => await withTempDir(async tempDir => {
    Nodefs.mkdirSync(Nodepath.join(tempDir, "client"), {
      recursive: true
    });
    Nodefs.writeFileSync(Nodepath.join(tempDir, "client", "open.js"), "export const openClient = true;\n");
    let manifest = helpers.getManifest(getManifestOptions(tempDir, {
      open: "client/open.js"
    }));
    let openEntry = getManifestEntry(manifest, "open");
    Buntest.expect(openEntry.rescriptFieldName).toBe("open_");
    let resTypeFile = helpers.getResTypeFileContent(manifest);
    expectContains(resTypeFile, `@as("open")`);
    expectContains(resTypeFile, "open_: string");
    let devAssetMap = helpers.getGeneratedDevAssetMap(manifest);
    return expectContains(devAssetMap, `"open": "/client/open.js"`);
  }));
});

exports.NodeFs = NodeFs;
exports.PluginTestHelpers = PluginTestHelpers;
exports.defaultClientEntryExtensions = defaultClientEntryExtensions;
exports.defaultEntryGlobs = defaultEntryGlobs;
exports.withTempDir = withTempDir;
exports.getManifestOptions = getManifestOptions;
exports.getManifestEntry = getManifestEntry;
exports.expectContains = expectContains;
/* modulePath Not a pure module */
