// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let H$ResX = require("../src/H.js");
let Hjsx$ResX = require("../src/Hjsx.js");
let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");

function card(title, author) {
  return Hjsx$ResX.Elements.jsxs("article", {
    children: [
      Hjsx$ResX.Elements.jsx("h2", {
        children: title
      }),
      Hjsx$ResX.Elements.jsx("p", {
        children: author
      }),
      Hjsx$ResX.Elements.jsx("footer", {
        children: "Read & enjoy"
      })
    ],
    className: "book"
  });
}

function catalog(count) {
  return Hjsx$ResX.Elements.jsxs("main", {
    children: [
      Hjsx$ResX.Elements.jsx("h1", {
        children: "Reading room"
      }),
      Stdlib_Array.fromInitializer(count, i => card(`Book ` + i.toString(), "A <writer>"))
    ],
    id: "catalog"
  });
}

function staticText() {
  return Hjsx$ResX.Elements.jsx("div", {
    children: "<&>\"' 🦊",
    title: "<&\"'"
  });
}

function captureOrder(visit) {
  return Hjsx$ResX.Elements.jsxs("div", {
    children: [
      Hjsx$ResX.Elements.jsx("span", {
        children: visit("first")
      }),
      Hjsx$ResX.Elements.jsx("span", {
        children: visit("second")
      })
    ]
  });
}

function fallback(css, value) {
  return Hjsx$ResX.Elements.jsxs("section", {
    children: [
      Hjsx$ResX.Elements.jsx("span", {
        children: value
      }),
      Hjsx$ResX.Elements.jsx("input", {
        disabled: true
      })
    ],
    className: css
  });
}

let context = H$ResX.Context.createContext("default");

let make = context.Provider;

let Provider = {
  make: make
};

function CompilerFixtures$Consumer(props) {
  return Hjsx$ResX.Elements.jsx("b", {
    children: H$ResX.Context.useContext(context)
  });
}

let Consumer = {
  make: CompilerFixtures$Consumer
};

function contextual(value) {
  return Hjsx$ResX.jsx(make, {
    value: value,
    children: Hjsx$ResX.Elements.jsx("div", {
      children: Hjsx$ResX.jsx(CompilerFixtures$Consumer, {})
    })
  });
}

async function make$1(param) {
  await Promise.resolve();
  return Hjsx$ResX.Elements.jsx("em", {
    children: param.value
  });
}

let CompilerFixtures$AsyncChild = make$1;

let AsyncChild = {
  make: CompilerFixtures$AsyncChild
};

function asynchronous(value) {
  return Hjsx$ResX.Elements.jsxs("div", {
    children: [
      Hjsx$ResX.jsx(CompilerFixtures$AsyncChild, {
        value: value
      }),
      Hjsx$ResX.Elements.jsx("span", {
        children: "after"
      })
    ]
  });
}

function literal() {
  return Hjsx$ResX.Elements.jsx("div", {
    children: "<safe> & sound",
    className: "",
    title: "A & B's"
  });
}

exports.card = card;
exports.catalog = catalog;
exports.staticText = staticText;
exports.captureOrder = captureOrder;
exports.fallback = fallback;
exports.context = context;
exports.Provider = Provider;
exports.Consumer = Consumer;
exports.contextual = contextual;
exports.AsyncChild = AsyncChild;
exports.asynchronous = asynchronous;
exports.literal = literal;
/* context Not a pure module */
