// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let H$ResX = require("../src/H.js");
let Buntest = require("bun:test");
let Hjsx$ResX = require("../src/Hjsx.js");

Buntest.describe("data prop rendering", () => {
  Buntest.test("regular data attribute still behaves as a string attribute", () => {
    let html = H$ResX.renderSyncToString(Hjsx$ResX.Elements.jsx("object", {
      data: "/preview.svg"
    }));
    Buntest.expect(html).toBe(`<object data="/preview.svg"></object>`);
  });
  Buntest.test("__rawProps emits arbitrary attributes", () => {
    let html = H$ResX.renderSyncToString(Hjsx$ResX.Elements.jsx("div", {
      __rawProps: {
        "hx-get": "/search",
        "aria-description": "From raw props",
        "x-flag": true
      }
    }));
    Buntest.expect(html).toBe(`<div hx-get="/search" aria-description="From raw props" x-flag="true"></div>`);
  });
  Buntest.test("__rawProps can override already bound JSX props by emitting duplicates later", () => {
    let html = H$ResX.renderSyncToString(Hjsx$ResX.Elements.jsx("div", {
      className: "from-typed",
      "data-testid": "from-typed",
      id: "from-typed",
      __rawProps: {
        id: "from-raw",
        class: "from-raw",
        "data-testid": "from-raw"
      }
    }));
    Buntest.expect(html).toBe(`<div class="from-typed" data-testid="from-typed" id="from-typed" id="from-raw" class="from-raw" data-testid="from-raw"></div>`);
  });
  Buntest.test("__rawProps skips invalid names and can not inject attributes", () => {
    let html = H$ResX.renderSyncToString(Hjsx$ResX.Elements.jsx("div", {
      __rawProps: {
        "bad name": "x",
        "\\\"onclick": "alert(1)",
        "safe-name": `\" autofocus=\"true\"`
      }
    }));
    Buntest.expect(html).toBe(`<div safe-name="&quot; autofocus=&quot;true&quot;"></div>`);
  });
  Buntest.test("__rawProps can emit duplicate typed data attribute", () => {
    let html = H$ResX.renderSyncToString(Hjsx$ResX.Elements.jsx("object", {
      data: "/from-typed.svg",
      __rawProps: {
        data: "/from-raw.svg"
      }
    }));
    Buntest.expect(html).toBe(`<object data="/from-typed.svg" data="/from-raw.svg"></object>`);
  });
});

/*  Not a pure module */
