// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib = require("@rescript/runtime/lib/js/Stdlib.js");
let Process = require("process");
let Dev$ResX = require("../src/Dev.js");
let Buntest = require("bun:test");
let Nodepath = require("node:path");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");

let modulePath = Nodepath.join(Process.cwd(), "res-x-vite-plugin.mjs");

let module_ = require(modulePath);

let helpers = module_.__test;

let makePlugin = module_.default;

let PluginTestHelpers = {
  modulePath: modulePath,
  module_: module_,
  helpers: helpers,
  makePlugin: makePlugin
};

function expectContains(text, substring) {
  Buntest.expect(text.includes(substring)).toBe(true);
}

function expectNotContains(text, substring) {
  Buntest.expect(text.includes(substring)).toBe(false);
}

function getProxyEntry(proxy, routePath) {
  let entry = proxy[routePath];
  if (entry !== undefined) {
    return Primitive_option.valFromOption(entry);
  } else {
    return Stdlib.panic(`Missing proxy entry for ` + routePath);
  }
}

Buntest.describe("dev helper", () => {
  Buntest.test("uses a same-origin dev socket and hard reloads after reconnect", () => {
    let script = Dev$ResX.getScript();
    expectContains(script, `window.location.host + "/_resx_dev"`);
    expectContains(script, "Server restarting...");
    expectContains(script, "window.location.reload()");
    expectContains(script, "document.body.appendChild");
    expectNotContains(script, "morphdom");
    expectNotContains(script, `http://localhost:9000/@vite/client`);
    expectNotContains(script, "fetch(document.location.href");
    expectNotContains(script, "Server connection opened.");
  });
  Buntest.test("generates root-relative dev asset urls", () => {
    let assetModuleSource = helpers.getGeneratedDevAssetMap([
      {
        fieldName: "styles_css",
        projectRelativePath: "assets/styles.css",
        sourcePath: "/Users/zth/OSS/res-x-4/assets/styles.css"
      },
      {
        fieldName: "resXClient_js",
        projectRelativePath: "node_modules/rescript-x/client/ResXClient.js",
        sourcePath: "/Users/zth/OSS/res-x-4/node_modules/rescript-x/client/ResXClient.js"
      },
      {
        fieldName: "external_client_js",
        projectRelativePath: undefined,
        sourcePath: "/tmp/resx/external-client.js"
      }
    ]);
    expectContains(assetModuleSource, `"/assets/styles.css"`);
    expectContains(assetModuleSource, `"/node_modules/rescript-x/client/ResXClient.js"`);
    expectContains(assetModuleSource, `"/@fs/tmp/resx/external-client.js"`);
    expectNotContains(assetModuleSource, "http://localhost");
  });
  Buntest.test("loads client-entry css links before importing the wrapper module", () => {
    let wrapper = helpers.getClientEntryWrapperModule("assets/client_loader.js", "assets/client.js", ["assets/admin.css"]);
    expectContains(wrapper, `link[rel="stylesheet"]`);
    expectContains(wrapper, `import("./client.js")`);
  });
  Buntest.test("disables Vite HMR while proxying the same-origin dev socket", () => {
    let plugin = makePlugin({
      resXClientLocation: "client/ResXClient.js",
      serverUri: "http://127.0.0.1:4444"
    });
    let config = plugin.config({
      server: {}
    }, {
      command: "serve"
    });
    Buntest.expect(config.server.hmr).toBe(false);
    Buntest.expect(getProxyEntry(config.server.proxy, "/_resx_dev").target).toBe("http://127.0.0.1:4445/");
  });
  Buntest.test("derives the proxied dev socket target from the app server uri", () => {
    Buntest.expect(helpers.getDevSocketProxyTarget("http://127.0.0.1:5555")).toBe("http://127.0.0.1:5556/");
    Buntest.expect(helpers.getDevSocketProxyTarget("https://example.test")).toBe("https://example.test:444/");
  });
});

exports.PluginTestHelpers = PluginTestHelpers;
exports.expectContains = expectContains;
exports.expectNotContains = expectNotContains;
exports.getProxyEntry = getProxyEntry;
/* modulePath Not a pure module */
