// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Buntest = require("bun:test");
let Handlers$ResX = require("../src/Handlers.js");
let TestUtils$ResX = require("./TestUtils.js");
let SecurityPolicy$ResX = require("../src/SecurityPolicy.js");

Buntest.describe("Endpoint handlers", () => {
  Buntest.test("prefixing of endpoint routes work", async () => {
    TestUtils$ResX.Handler.testHandler.endpointGet("/endpoint-test", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, param => "nope", undefined, undefined, undefined, "/_api/endpoint-test");
    let text = await response.text();
    Buntest.expect(text).toBe("Test!");
  });
  Buntest.test("security policy can block endpoint responses", async () => {
    TestUtils$ResX.Handler.testHandler.endpointGet("/endpoint-test-block", async param => ({
      TAG: "Block",
      code: 403,
      message: "Forbidden"
    }), async param => new Response("Test!"), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/endpoint-test-block");
    let text = await response.text();
    Buntest.expect(text).toBe("Forbidden");
    Buntest.expect(response.status).toBe(403);
  });
  Buntest.test("security policy metadata is forwarded to endpoint handlers", async () => {
    TestUtils$ResX.Handler.testHandler.endpointGet("/endpoint-test-meta", async param => ({
      TAG: "Allow",
      _0: "meta"
    }), async param => new Response(param.securityPolicyData), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/endpoint-test-meta");
    let text = await response.text();
    Buntest.expect(text).toBe("meta");
  });
  Buntest.test("duplicate endpoint registrations keep the first handler", async () => {
    TestUtils$ResX.Handler.testHandler.endpointGet("/endpoint-test-duplicate-first-wins", SecurityPolicy$ResX.allow, async param => new Response("First"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointGet("/endpoint-test-duplicate-first-wins", SecurityPolicy$ResX.allow, async param => new Response("Second"), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/endpoint-test-duplicate-first-wins");
    let text = await response.text();
    Buntest.expect(text).toBe("First");
  });
  Buntest.test("direct POST, PUT, DELETE, and PATCH endpoint registration works", async () => {
    TestUtils$ResX.Handler.testHandler.endpointPost("/endpoint-test-post-direct", SecurityPolicy$ResX.allow, async param => new Response("POST direct"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointPut("/endpoint-test-put-direct", SecurityPolicy$ResX.allow, async param => new Response("PUT direct"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointDelete("/endpoint-test-delete-direct", SecurityPolicy$ResX.allow, async param => new Response("DELETE direct"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointPatch("/endpoint-test-patch-direct", SecurityPolicy$ResX.allow, async param => new Response("PATCH direct"), undefined);
    let postResponse = await TestUtils$ResX.getResponse("POST", undefined, undefined, undefined, undefined, "/_api/endpoint-test-post-direct");
    let putResponse = await TestUtils$ResX.getResponse("PUT", undefined, undefined, undefined, undefined, "/_api/endpoint-test-put-direct");
    let deleteResponse = await TestUtils$ResX.getResponse("DELETE", undefined, undefined, undefined, undefined, "/_api/endpoint-test-delete-direct");
    let patchResponse = await TestUtils$ResX.getResponse("PATCH", undefined, undefined, undefined, undefined, "/_api/endpoint-test-patch-direct");
    let postText = await postResponse.text();
    let putText = await putResponse.text();
    let deleteText = await deleteResponse.text();
    let patchText = await patchResponse.text();
    Buntest.expect(postText).toBe("POST direct");
    Buntest.expect(putText).toBe("PUT direct");
    Buntest.expect(deleteText).toBe("DELETE direct");
    Buntest.expect(patchText).toBe("PATCH direct");
  });
  Buntest.test("delaying endpoint implementations works", async () => {
    let getHandler = TestUtils$ResX.Handler.testHandler.endpointGetRef("/endpoint-test-delay-get");
    let postHandler = TestUtils$ResX.Handler.testHandler.endpointPostRef("/endpoint-test-delay-post");
    let putHandler = TestUtils$ResX.Handler.testHandler.endpointPutRef("/endpoint-test-delay-put");
    let deleteHandler = TestUtils$ResX.Handler.testHandler.endpointDeleteRef("/endpoint-test-delay-delete");
    let patchHandler = TestUtils$ResX.Handler.testHandler.endpointPatchRef("/endpoint-test-delay-patch");
    TestUtils$ResX.Handler.testHandler.endpointGetDefine(getHandler, SecurityPolicy$ResX.allow, async param => new Response("GET delayed"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointPostDefine(postHandler, SecurityPolicy$ResX.allow, async param => new Response("POST delayed"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointPutDefine(putHandler, SecurityPolicy$ResX.allow, async param => new Response("PUT delayed"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointDeleteDefine(deleteHandler, SecurityPolicy$ResX.allow, async param => new Response("DELETE delayed"), undefined);
    TestUtils$ResX.Handler.testHandler.endpointPatchDefine(patchHandler, SecurityPolicy$ResX.allow, async param => new Response("PATCH delayed"), undefined);
    let getResponseResult = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/endpoint-test-delay-get");
    let postResponse = await TestUtils$ResX.getResponse("POST", undefined, undefined, undefined, undefined, "/_api/endpoint-test-delay-post");
    let putResponse = await TestUtils$ResX.getResponse("PUT", undefined, undefined, undefined, undefined, "/_api/endpoint-test-delay-put");
    let deleteResponse = await TestUtils$ResX.getResponse("DELETE", undefined, undefined, undefined, undefined, "/_api/endpoint-test-delay-delete");
    let patchResponse = await TestUtils$ResX.getResponse("PATCH", undefined, undefined, undefined, undefined, "/_api/endpoint-test-delay-patch");
    let getText = await getResponseResult.text();
    let postText = await postResponse.text();
    let putText = await putResponse.text();
    let deleteText = await deleteResponse.text();
    let patchText = await patchResponse.text();
    Buntest.expect(getText).toBe("GET delayed");
    Buntest.expect(postText).toBe("POST delayed");
    Buntest.expect(putText).toBe("PUT delayed");
    Buntest.expect(deleteText).toBe("DELETE delayed");
    Buntest.expect(patchText).toBe("PATCH delayed");
  });
  Buntest.test("endpoint URL helpers return the correct URLs", async () => {
    let getHandler = TestUtils$ResX.Handler.testHandler.endpointGet("/endpoint-test-url-get", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    let postHandler = TestUtils$ResX.Handler.testHandler.endpointPost("/endpoint-test-url-post", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    let putHandler = TestUtils$ResX.Handler.testHandler.endpointPut("/endpoint-test-url-put", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    let deleteHandler = TestUtils$ResX.Handler.testHandler.endpointDelete("/endpoint-test-url-delete", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    let patchHandler = TestUtils$ResX.Handler.testHandler.endpointPatch("/endpoint-test-url-patch", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    Buntest.expect(Handlers$ResX.endpointGetToEndpointURL(getHandler)).toBe("/_api/endpoint-test-url-get");
    Buntest.expect(Handlers$ResX.endpointPostToEndpointURL(postHandler)).toBe("/_api/endpoint-test-url-post");
    Buntest.expect(Handlers$ResX.endpointPutToEndpointURL(putHandler)).toBe("/_api/endpoint-test-url-put");
    Buntest.expect(Handlers$ResX.endpointDeleteToEndpointURL(deleteHandler)).toBe("/_api/endpoint-test-url-delete");
    Buntest.expect(Handlers$ResX.endpointPatchToEndpointURL(patchHandler)).toBe("/_api/endpoint-test-url-patch");
  });
});

/*  Not a pure module */
