// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Buntest = require("bun:test");
let TestUtils$ResX = require("./TestUtils.js");
let SecurityPolicy$ResX = require("../src/SecurityPolicy.js");

Buntest.describe("Form action handlers", () => {
  Buntest.test("prefixing of form action handler routes work", async () => {
    TestUtils$ResX.Handler.testHandler.formAction("/test", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, param => "nope", undefined, undefined, undefined, "/_form/test");
    let text = await response.text();
    Buntest.expect(text).toBe(`Test!`);
  });
  Buntest.test("security policy metadata is forwarded to handler", async () => {
    TestUtils$ResX.Handler.testHandler.formAction("/test-meta", async param => ({
      TAG: "Allow",
      _0: 42
    }), async param => new Response(param.securityPolicyData.toString()), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, param => "nope", undefined, undefined, undefined, "/_form/test-meta");
    let text = await response.text();
    Buntest.expect(text).toBe(`42`);
  });
  Buntest.test("duplicate form action registrations keep the first handler", async () => {
    TestUtils$ResX.Handler.testHandler.formAction("/test-duplicate-first-wins", SecurityPolicy$ResX.allow, async param => new Response("First"), undefined);
    TestUtils$ResX.Handler.testHandler.formAction("/test-duplicate-first-wins", SecurityPolicy$ResX.allow, async param => new Response("Second"), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, param => "nope", undefined, undefined, undefined, "/_form/test-duplicate-first-wins");
    let text = await response.text();
    Buntest.expect(text).toBe(`First`);
  });
});

/*  Not a pure module */
