// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Buntest = require("bun:test");
var Handlers$ResX = require("../src/Handlers.js");
var TestUtils$ResX = require("./TestUtils.js");
var SecurityPolicy$ResX = require("../src/SecurityPolicy.js");

Buntest.describe("Form action handlers", (function () {
        Buntest.test("prefixing of form action handler routes work", (async function () {
                Handlers$ResX.formAction(TestUtils$ResX.Handler.testHandler, "/test", SecurityPolicy$ResX.allow, (async function (param) {
                        return new Response("Test!");
                      }));
                var response = await TestUtils$ResX.getResponse(undefined, (function (param) {
                        return "nope";
                      }), undefined, undefined, undefined, "/_form/test");
                var text = await response.text();
                Buntest.expect(text).toBe("Test!");
              }));
      }));

/*  Not a pure module */
