// Generated by ReScript, PLEASE EDIT WITH CARE

let Buntest = require("bun:test");
let Handlers$ResX = require("../src/Handlers.js");
let TestUtils$ResX = require("./TestUtils.js");
let SecurityPolicy$ResX = require("../src/SecurityPolicy.js");

Buntest.describe("Form action handlers", () => {
  Buntest.test("prefixing of form action handler routes work", async () => {
    Handlers$ResX.formAction(TestUtils$ResX.Handler.testHandler, "/test", SecurityPolicy$ResX.allow, async param => new Response("Test!"), undefined);
    let response = await TestUtils$ResX.getResponse(undefined, param => "nope", undefined, undefined, undefined, "/_form/test");
    let text = await response.text();
    Buntest.expect(text).toBe(`Test!`);
  });
});

export {
  
}
/*  Not a pure module */
