// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var H$ResX = require("../src/H.js");
var Buntest = require("bun:test");
var Hjsx$ResX = require("../src/Hjsx.js");

Buntest.describe("rendering HTML via JSX", (function () {
        Buntest.test("HTML is escaped", (function () {
                var dangerousHtml = "<script>alert(\"hello!\")</script>";
                var jsx = Hjsx$ResX.Elements.jsx("div", {
                      children: dangerousHtml
                    });
                Buntest.expect(H$ResX.renderSyncToString(jsx)).toBe("<div>" + Bun.escapeHTML(dangerousHtml) + "</div>");
              }));
      }));

/*  Not a pure module */
