// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let H$ResX = require("../src/H.js");
let Buntest = require("bun:test");
let Hjsx$ResX = require("../src/Hjsx.js");

Buntest.describe("rendering HTML via JSX", () => {
  Buntest.test("HTML is escaped", () => {
    let dangerousHtml = `<script>alert("hello!")</script>`;
    let jsx = Hjsx$ResX.Elements.jsx("div", {
      children: dangerousHtml
    });
    Buntest.expect(H$ResX.renderSyncToString(jsx)).toBe(`<div>` + Bun.escapeHTML(dangerousHtml) + `</div>`);
  });
});

/*  Not a pure module */
