// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Buntest = require("bun:test");
let Handlers$ResX = require("../src/Handlers.js");
let TestUtils$ResX = require("./TestUtils.js");
let SecurityPolicy$ResX = require("../src/SecurityPolicy.js");

Buntest.describe("HTMX handlers", () => {
  Buntest.test("prefixing of HTMX handler routes work", async () => {
    TestUtils$ResX.Handler.testHandler.hxGet("/test", SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let response = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/test");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>Test!`);
  });
  Buntest.test("security policy can block content", async () => {
    TestUtils$ResX.Handler.testHandler.hxGet("/test-block", async param => ({
      TAG: "Block",
      code: 403,
      message: "Forbidden"
    }), async param => "Test!", undefined);
    let response = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/test-block");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>Forbidden`);
    Buntest.expect(response.status).toBe(403);
  });
  Buntest.test("security policy metadata is forwarded to handler", async () => {
    TestUtils$ResX.Handler.testHandler.hxGet("/test-meta", async param => ({
      TAG: "Allow",
      _0: "meta"
    }), async param => param.securityPolicyData, undefined);
    let response = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/test-meta");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>meta`);
  });
  Buntest.test("delaying GET handler implementation works", async () => {
    let getHandler = TestUtils$ResX.Handler.testHandler.hxGetRef("/test-delay");
    TestUtils$ResX.Handler.testHandler.hxGetDefine(getHandler, SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let response = await TestUtils$ResX.getResponse(undefined, undefined, undefined, undefined, undefined, "/_api/test-delay");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>Test!`);
  });
  Buntest.test("delaying POST handler implementation works", async () => {
    let postHandler = TestUtils$ResX.Handler.testHandler.hxPostRef("/test-delay");
    TestUtils$ResX.Handler.testHandler.hxPostDefine(postHandler, SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let response = await TestUtils$ResX.getResponse("POST", undefined, undefined, undefined, undefined, "/_api/test-delay");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>Test!`);
  });
  Buntest.test("delaying PUT handler implementation works", async () => {
    let putHandler = TestUtils$ResX.Handler.testHandler.hxPutRef("/test-delay");
    TestUtils$ResX.Handler.testHandler.hxPutDefine(putHandler, SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let response = await TestUtils$ResX.getResponse("PUT", undefined, undefined, undefined, undefined, "/_api/test-delay");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>Test!`);
  });
  Buntest.test("delaying DELETE handler implementation works", async () => {
    let deleteHandler = TestUtils$ResX.Handler.testHandler.hxDeleteRef("/test-delay");
    TestUtils$ResX.Handler.testHandler.hxDeleteDefine(deleteHandler, SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let response = await TestUtils$ResX.getResponse("DELETE", undefined, undefined, undefined, undefined, "/_api/test-delay");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>Test!`);
  });
  Buntest.test("delaying PATCH handler implementation works", async () => {
    let patchHandler = TestUtils$ResX.Handler.testHandler.hxPatchRef("/test-delay");
    TestUtils$ResX.Handler.testHandler.hxPatchDefine(patchHandler, SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let response = await TestUtils$ResX.getResponse("PATCH", undefined, undefined, undefined, undefined, "/_api/test-delay");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>Test!`);
  });
  Buntest.test("endpoint URL helpers return the correct URLs", async () => {
    let getHandler = TestUtils$ResX.Handler.testHandler.hxGet("/test-url-get", SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let postHandler = TestUtils$ResX.Handler.testHandler.hxPost("/test-url-post", SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let putHandler = TestUtils$ResX.Handler.testHandler.hxPut("/test-url-put", SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let deleteHandler = TestUtils$ResX.Handler.testHandler.hxDelete("/test-url-delete", SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let patchHandler = TestUtils$ResX.Handler.testHandler.hxPatch("/test-url-patch", SecurityPolicy$ResX.allow, async param => "Test!", undefined);
    let formActionHandler = TestUtils$ResX.Handler.testHandler.formAction("/test-form", SecurityPolicy$ResX.allow, async param => Response.redirect("/test"), undefined);
    Buntest.expect(Handlers$ResX.hxGetToEndpointURL(getHandler)).toBe("/_api/test-url-get");
    Buntest.expect(Handlers$ResX.hxPostToEndpointURL(postHandler)).toBe("/_api/test-url-post");
    Buntest.expect(Handlers$ResX.hxPutToEndpointURL(putHandler)).toBe("/_api/test-url-put");
    Buntest.expect(Handlers$ResX.hxDeleteToEndpointURL(deleteHandler)).toBe("/_api/test-url-delete");
    Buntest.expect(Handlers$ResX.hxPatchToEndpointURL(patchHandler)).toBe("/_api/test-url-patch");
    Buntest.expect(Handlers$ResX.FormAction.toEndpointURL(formActionHandler)).toBe("/_form/test-form");
  });
});

/*  Not a pure module */
