// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Buntest = require("bun:test");
let Handlers$ResX = require("../src/Handlers.js");
let TestUtils$ResX = require("./TestUtils.js");
let SecurityPolicy$ResX = require("../src/SecurityPolicy.js");

function makeCollisionHandler() {
  return Handlers$ResX.make(async param => ({
    shouldAppendToHead: false
  }), {
    htmxApiPrefix: "/_shared",
    formActionHandlerApiPrefix: "/_shared"
  });
}

Buntest.describe("route collisions", () => {
  Buntest.test("formAction takes precedence over HTMX GET and POST routes on the same path", async () => {
    let handler = makeCollisionHandler();
    handler.hxGet("/collision-form-after-htmx", SecurityPolicy$ResX.allow, async param => "HTMX GET", undefined);
    handler.hxPost("/collision-form-after-htmx", SecurityPolicy$ResX.allow, async param => "HTMX POST", undefined);
    handler.formAction("/collision-form-after-htmx", SecurityPolicy$ResX.allow, async param => new Response("FORM"), undefined);
    let getResponse = await TestUtils$ResX.getResponseForHandler(handler, undefined, undefined, undefined, undefined, undefined, "/_shared/collision-form-after-htmx");
    let postResponse = await TestUtils$ResX.getResponseForHandler(handler, "POST", undefined, undefined, undefined, undefined, "/_shared/collision-form-after-htmx");
    let getText = await getResponse.text();
    let postText = await postResponse.text();
    Buntest.expect(getText).toBe("FORM");
    Buntest.expect(postText).toBe("FORM");
  });
  Buntest.test("existing formAction route takes precedence when HTMX routes are added later", async () => {
    let handler = makeCollisionHandler();
    handler.formAction("/collision-htmx-after-form", SecurityPolicy$ResX.allow, async param => new Response("FORM"), undefined);
    handler.hxGet("/collision-htmx-after-form", SecurityPolicy$ResX.allow, async param => "HTMX GET", undefined);
    handler.hxPost("/collision-htmx-after-form", SecurityPolicy$ResX.allow, async param => "HTMX POST", undefined);
    let getResponse = await TestUtils$ResX.getResponseForHandler(handler, undefined, undefined, undefined, undefined, undefined, "/_shared/collision-htmx-after-form");
    let postResponse = await TestUtils$ResX.getResponseForHandler(handler, "POST", undefined, undefined, undefined, undefined, "/_shared/collision-htmx-after-form");
    let getText = await getResponse.text();
    let postText = await postResponse.text();
    Buntest.expect(getText).toBe("FORM");
    Buntest.expect(postText).toBe("FORM");
  });
  Buntest.test("formAction takes precedence over endpoint GET and POST routes on the same path", async () => {
    let handler = makeCollisionHandler();
    handler.endpointGet("/collision-form-after-endpoint", SecurityPolicy$ResX.allow, async param => new Response("ENDPOINT GET"), undefined);
    handler.endpointPost("/collision-form-after-endpoint", SecurityPolicy$ResX.allow, async param => new Response("ENDPOINT POST"), undefined);
    handler.formAction("/collision-form-after-endpoint", SecurityPolicy$ResX.allow, async param => new Response("FORM"), undefined);
    let getResponse = await TestUtils$ResX.getResponseForHandler(handler, undefined, undefined, undefined, undefined, undefined, "/_shared/collision-form-after-endpoint");
    let postResponse = await TestUtils$ResX.getResponseForHandler(handler, "POST", undefined, undefined, undefined, undefined, "/_shared/collision-form-after-endpoint");
    let getText = await getResponse.text();
    let postText = await postResponse.text();
    Buntest.expect(getText).toBe("FORM");
    Buntest.expect(postText).toBe("FORM");
  });
  Buntest.test("existing formAction route takes precedence when endpoint routes are added later", async () => {
    let handler = makeCollisionHandler();
    handler.formAction("/collision-endpoint-after-form", SecurityPolicy$ResX.allow, async param => new Response("FORM"), undefined);
    handler.endpointGet("/collision-endpoint-after-form", SecurityPolicy$ResX.allow, async param => new Response("ENDPOINT GET"), undefined);
    handler.endpointPost("/collision-endpoint-after-form", SecurityPolicy$ResX.allow, async param => new Response("ENDPOINT POST"), undefined);
    let getResponse = await TestUtils$ResX.getResponseForHandler(handler, undefined, undefined, undefined, undefined, undefined, "/_shared/collision-endpoint-after-form");
    let postResponse = await TestUtils$ResX.getResponseForHandler(handler, "POST", undefined, undefined, undefined, undefined, "/_shared/collision-endpoint-after-form");
    let getText = await getResponse.text();
    let postText = await postResponse.text();
    Buntest.expect(getText).toBe("FORM");
    Buntest.expect(postText).toBe("FORM");
  });
  Buntest.test("existing HTMX route keeps the API path when an endpoint is added later", async () => {
    let handler = makeCollisionHandler();
    handler.hxGet("/collision-api-kind-first", SecurityPolicy$ResX.allow, async param => "HTMX", undefined);
    handler.endpointGet("/collision-api-kind-first", SecurityPolicy$ResX.allow, async param => new Response("ENDPOINT"), undefined);
    let response = await TestUtils$ResX.getResponseForHandler(handler, undefined, undefined, undefined, undefined, undefined, "/_shared/collision-api-kind-first");
    let text = await response.text();
    Buntest.expect(text).toBe(`<!DOCTYPE html>HTMX`);
  });
  Buntest.test("existing endpoint route keeps the API path when HTMX is added later", async () => {
    let handler = makeCollisionHandler();
    handler.endpointGet("/collision-api-kind-second", SecurityPolicy$ResX.allow, async param => new Response("ENDPOINT"), undefined);
    handler.hxGet("/collision-api-kind-second", SecurityPolicy$ResX.allow, async param => "HTMX", undefined);
    let response = await TestUtils$ResX.getResponseForHandler(handler, undefined, undefined, undefined, undefined, undefined, "/_shared/collision-api-kind-second");
    let text = await response.text();
    Buntest.expect(text).toBe("ENDPOINT");
  });
});

exports.makeCollisionHandler = makeCollisionHandler;
/*  Not a pure module */
