// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let H$ResX = require("../src/H.js");
let Buntest = require("bun:test");
let Hjsx$ResX = require("../src/Hjsx.js");

Buntest.describe("style prop handling", () => {
  Buntest.test("emits the expected style string", () => {
    Buntest.expect(H$ResX.renderSyncToString(Hjsx$ResX.Elements.jsx("div", {
      style: {
        color: "red"
      }
    }))).toBe(`<div style="color:red;"></div>`);
  });
});

/*  Not a pure module */
