// Generated by ResX, do not edit manually

type assets = {
  /** ResX Client Bundle */
  resXClient_js: string,

  /** `images/logo.png` */
  images__logo_png: string,

  /** `main.ts` */
  main_ts: string,

  /** `misc/data.txt` */
  misc__data_txt: string,

  /** `styles.css` */
  styles_css: string,
}

@module("./res-x-assets.js") external assets: assets = "assets"
