// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let ResXAssetsJs = require("./res-x-assets.js");
let ResXStaticRoutesJs = require("./res-x-static-routes.js");

let assets = ResXAssetsJs.assets;

let staticAssetRoutes = ResXStaticRoutesJs.staticAssetRoutes;

exports.assets = assets;
exports.staticAssetRoutes = staticAssetRoutes;
/* assets Not a pure module */
