// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResXAssetsJs = require("./res-x-assets.js");

var assets = ResXAssetsJs.assets;

exports.assets = assets;
/* assets Not a pure module */
