// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Hjsx$ResX = require("rescript-x/src/Hjsx.js");

function Catalog(props) {
  return Hjsx$ResX.Elements.jsxs("main", {
    children: [
      Hjsx$ResX.Elements.jsx("h1", {
        children: "The reading room",
        className: "text-3xl font-bold"
      }),
      Hjsx$ResX.Elements.jsx("p", {
        children: "A few books for your next quiet afternoon.",
        className: "my-4"
      }),
      Hjsx$ResX.Elements.jsx("section", {
        children: [
          [
            "The Left Hand of Darkness",
            "Ursula K. Le Guin"
          ],
          [
            "Piranesi",
            "Susanna Clarke"
          ],
          [
            "Invisible Cities",
            "Italo Calvino"
          ]
        ].map(param => Hjsx$ResX.Elements.jsxs("article", {
          children: [
            Hjsx$ResX.Elements.jsx("h2", {
              children: param[0],
              className: "text-xl font-semibold"
            }),
            Hjsx$ResX.Elements.jsx("p", {
              children: param[1],
              className: "text-gray-600"
            })
          ],
          className: "border rounded-lg p-5"
        })),
        className: "grid gap-4"
      })
    ],
    className: "max-w-3xl mx-auto p-8"
  });
}

let make = Catalog;

exports.make = make;
/* Hjsx-ResX Not a pure module */
