// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Hjsx$ResX = require("rescript-x/src/Hjsx.js");

function wait() {
  return new Promise((function (resolve, _reject) {
                setTimeout((function () {
                        resolve();
                      }), 1000);
              }));
}

async function make(param) {
  await wait();
  return Hjsx$ResX.Elements.jsxs("div", {
              children: [
                "This was deferred.",
                Hjsx$ResX.Elements.jsx("div", {
                      children: param.children
                    })
              ]
            });
}

var DeferredComponent = make;

var make$1 = DeferredComponent;

exports.wait = wait;
exports.make = make$1;
/* Hjsx-ResX Not a pure module */
