// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Html = require("./Html.js");
var SiteMap = require("./SiteMap.js");
var BunUtils = require("res-x/src/BunUtils.js");
var FourOhFour = require("./FourOhFour.js");
var $$Navigation = require("./Navigation.js");
var UserRoutes = require("./UserRoutes.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var HtmxHandler = require("./HtmxHandler.js");
var ResX__React = require("res-x/src/ResX__React.js");
var ResX__Handlers = require("res-x/src/ResX__Handlers.js");
var ResX__ReactDOM = require("res-x/src/ResX__ReactDOM.js");
var ResX__RequestController = require("res-x/src/ResX__RequestController.js");

var server = Bun.serve({
      development: BunUtils.isDev,
      port: 4444,
      fetch: (async function (request, server) {
          var staticResponse = await BunUtils.serveStaticFile(request);
          if (staticResponse !== undefined) {
            return Caml_option.valFromOption(staticResponse);
          } else {
            return await ResX__Handlers.handleRequest(HtmxHandler.handler, {
                        request: request,
                        server: server,
                        render: (async function (param) {
                            var requestController = param.requestController;
                            var path = param.path;
                            var headers = param.headers;
                            var exit = 0;
                            if (path && path.hd === "sitemap.xml") {
                              if (!path.tl) {
                                return ResX__React.jsx(SiteMap.make, {});
                              }
                              exit = 1;
                            } else {
                              exit = 1;
                            }
                            if (exit === 1) {
                              ResX__RequestController.appendTitleSegment(requestController, "Test App");
                              var tmp;
                              var exit$1 = 0;
                              if (path) {
                                var exit$2 = 0;
                                switch (path.hd) {
                                  case "moved" :
                                      tmp = path.tl ? ResX__React.jsx(FourOhFour.make, {
                                              setGenericTitle: true
                                            }) : ResX__RequestController.redirect(requestController, "/start", 302);
                                      break;
                                  case "" :
                                  case "start" :
                                      exit$2 = 3;
                                      break;
                                  case "user" :
                                      tmp = UserRoutes.match(path.tl, headers, requestController);
                                      break;
                                  default:
                                    tmp = ResX__React.jsx(FourOhFour.make, {
                                          setGenericTitle: true
                                        });
                                }
                                if (exit$2 === 3) {
                                  if (path.tl) {
                                    tmp = ResX__React.jsx(FourOhFour.make, {
                                          setGenericTitle: true
                                        });
                                  } else {
                                    exit$1 = 2;
                                  }
                                }
                                
                              } else {
                                exit$1 = 2;
                              }
                              if (exit$1 === 2) {
                                headers.set("Cache-Control", "public, immutable, max-age=900");
                                tmp = ResX__ReactDOM.jsx("div", {
                                      children: "Start page!"
                                    });
                              }
                              return ResX__React.jsx(Html.make, {
                                          children: ResX__ReactDOM.jsxs("div", {
                                                children: [
                                                  ResX__React.jsx($$Navigation.make, {}),
                                                  tmp
                                                ]
                                              })
                                        });
                            }
                            
                          }),
                        setupHeaders: (function () {
                            return new Headers([[
                                          "Content-Type",
                                          "text/html"
                                        ]]);
                          })
                      });
          }
        })
    });

var portString = server.port.toString();

console.log("Listening! on localhost:" + portString);

if (BunUtils.isDev) {
  BunUtils.runDevServer(4444);
}

var port = 4444;

exports.port = port;
exports.server = server;
exports.portString = portString;
/* server Not a pure module */
