// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Html = require("./Html.js");
let SiteMap = require("./SiteMap.js");
let Hjsx$ResX = require("rescript-x/src/Hjsx.js");
let FourOhFour = require("./FourOhFour.js");
let Navigation = require("./Navigation.js");
let ResXAssets = require("./__generated__/ResXAssets.js");
let UserRoutes = require("./UserRoutes.js");
let HtmxHandler = require("./HtmxHandler.js");
let BunUtils$ResX = require("rescript-x/src/BunUtils.js");
let Handlers$ResX = require("rescript-x/src/Handlers.js");
let RequestController$ResX = require("rescript-x/src/RequestController.js");

let server = Bun.serve({
  development: BunUtils$ResX.isDev,
  port: 4444,
  fetch: async (request, _server) => await Handlers$ResX.handleRequest(HtmxHandler.handler, {
    request: request,
    render: async param => {
      let requestController = param.requestController;
      let path = param.path;
      let headers = param.headers;
      let exit = 0;
      if (path !== 0 && path.hd === "sitemap.xml") {
        if (path.tl === 0) {
          return Hjsx$ResX.jsx(SiteMap.make, {});
        }
        exit = 1;
      } else {
        exit = 1;
      }
      if (exit === 1) {
        RequestController$ResX.appendTitleSegment(requestController, "Test App");
        let tmp;
        let exit$1 = 0;
        if (path !== 0) {
          let exit$2 = 0;
          switch (path.hd) {
            case "moved" :
              tmp = path.tl !== 0 ? Hjsx$ResX.jsx(FourOhFour.make, {
                  setGenericTitle: true
                }) : RequestController$ResX.redirect(requestController, "/start", 302);
              break;
            case "" :
            case "start" :
              exit$2 = 3;
              break;
            case "user" :
              tmp = UserRoutes.match(path.tl, headers, requestController);
              break;
            default:
              tmp = Hjsx$ResX.jsx(FourOhFour.make, {
                setGenericTitle: true
              });
          }
          if (exit$2 === 3) {
            if (path.tl !== 0) {
              tmp = Hjsx$ResX.jsx(FourOhFour.make, {
                setGenericTitle: true
              });
            } else {
              exit$1 = 2;
            }
          }
        } else {
          exit$1 = 2;
        }
        if (exit$1 === 2) {
          headers.set("Cache-Control", "public, immutable, max-age=900");
          tmp = Hjsx$ResX.Elements.jsx("div", {
            children: "Start page!"
          });
        }
        return Hjsx$ResX.jsxs(Html.make, {
          children: [
            Hjsx$ResX.jsx(Navigation.make, {}),
            Hjsx$ResX.Elements.jsx("div", {
              children: tmp
            })
          ]
        });
      }
    },
    setupHeaders: () => new Headers([[
        "Content-Type",
        "text/html"
      ]])
  }),
  routes: ResXAssets.staticAssetRoutes
});

let portString = server.port.toString();

console.log(`Listening! on localhost:` + portString);

if (BunUtils$ResX.isDev) {
  BunUtils$ResX.runDevServer(4444);
}

let port = 4444;

exports.port = port;
exports.server = server;
exports.portString = portString;
/* server Not a pure module */
