// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResX__ReactDOM$ResX = require("rescript-x/src/ResX__ReactDOM.js");

function ErrorMessage(props) {
  return ResX__ReactDOM$ResX.jsx("div", {
              children: props.message
            });
}

var make = ErrorMessage;

exports.make = make;
/* ResX__ReactDOM-ResX Not a pure module */
