// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Hjsx$ResX = require("rescript-x/src/Hjsx.js");

function ErrorMessage(props) {
  return Hjsx$ResX.Elements.jsx("div", {
              children: props.message
            });
}

var make = ErrorMessage;

exports.make = make;
/* Hjsx-ResX Not a pure module */
