// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Demo = require("./Demo.js");
let StaticExporter$ResX = require("rescript-x/src/StaticExporter.js");

let urls = [
  "/",
  "/start",
  "/user/1"
];

StaticExporter$ResX.run(Demo.server, urls);

exports.urls = urls;
/*  Not a pure module */
