// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");

function FailingComponent(props) {
  return Js_exn.raiseError("Error!");
}

var make = FailingComponent;

exports.make = make;
/* No side effect */
