// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib_JsError = require("@rescript/runtime/lib/js/Stdlib_JsError.js");

function FailingComponent(props) {
  return Stdlib_JsError.throwWithMessage("Error!");
}

let make = FailingComponent;

exports.make = make;
/* No side effect */
