// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Hjsx$ResX = require("rescript-x/src/Hjsx.js");
let HtmxHandler = require("./HtmxHandler.js");

function FourOhFour(props) {
  let __setGenericTitle = props.setGenericTitle;
  let setGenericTitle = __setGenericTitle !== undefined ? __setGenericTitle : false;
  let context = HtmxHandler.useContext();
  context.requestController.setStatus(404);
  if (setGenericTitle) {
    context.requestController.setFullTitle("Not Found");
  }
  return Hjsx$ResX.Elements.jsx("div", {
    children: "404"
  });
}

let make = FourOhFour;

exports.make = make;
/* Hjsx-ResX Not a pure module */
