// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Hjsx$ResX = require("rescript-x/src/Hjsx.js");
let HtmxHandler = require("./HtmxHandler.js");
let RequestController$ResX = require("rescript-x/src/RequestController.js");

function FourOhFour(props) {
  let __setGenericTitle = props.setGenericTitle;
  let setGenericTitle = __setGenericTitle !== undefined ? __setGenericTitle : false;
  let context = HtmxHandler.useContext();
  RequestController$ResX.setStatus(context.requestController, 404);
  if (setGenericTitle) {
    RequestController$ResX.setFullTitle(context.requestController, "Not Found");
  }
  return Hjsx$ResX.Elements.jsx("div", {
    children: "404"
  });
}

let make = FourOhFour;

exports.make = make;
/* Hjsx-ResX Not a pure module */
