// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Handlers$ResX = require("rescript-x/src/Handlers.js");
var ResX__ReactDOM$ResX = require("rescript-x/src/ResX__ReactDOM.js");
var RequestController$ResX = require("rescript-x/src/RequestController.js");

function Head(props) {
  return ResX__ReactDOM$ResX.jsx("head", {
              children: props.children
            });
}

function Head$RenderInHead(props) {
  var ctx = Handlers$ResX.useContext(props.handler);
  RequestController$ResX.appendToHead(ctx.requestController, props.children);
  return null;
}

var RenderInHead = {
  make: Head$RenderInHead
};

var make = Head;

exports.make = make;
exports.RenderInHead = RenderInHead;
/* Handlers-ResX Not a pure module */
