// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Hjsx$ResX = require("rescript-x/src/Hjsx.js");
let Handlers$ResX = require("rescript-x/src/Handlers.js");
let RequestController$ResX = require("rescript-x/src/RequestController.js");

function Head(props) {
  return Hjsx$ResX.Elements.jsx("head", {
    children: props.children
  });
}

function Head$RenderInHead(props) {
  let ctx = Handlers$ResX.useContext(props.handler);
  RequestController$ResX.appendToHead(ctx.requestController, props.children);
  return null;
}

let RenderInHead = {
  make: Head$RenderInHead
};

let make = Head;

exports.make = make;
exports.RenderInHead = RenderInHead;
/* Hjsx-ResX Not a pure module */
