// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResX__Handlers = require("rescript-x/src/ResX__Handlers.js");
var ResX__ReactDOM = require("rescript-x/src/ResX__ReactDOM.js");
var ResX__RequestController = require("rescript-x/src/ResX__RequestController.js");

function Head(props) {
  return ResX__ReactDOM.jsx("head", {
              children: props.children
            });
}

function Head$RenderInHead(props) {
  var ctx = ResX__Handlers.useContext(props.handler);
  ResX__RequestController.appendToHead(ctx.requestController, props.children);
  return null;
}

var RenderInHead = {
  make: Head$RenderInHead
};

var make = Head;

exports.make = make;
exports.RenderInHead = RenderInHead;
/* ResX__Handlers Not a pure module */
