// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Hjsx$ResX = require("rescript-x/src/Hjsx.js");
let Htmx$ResX = require("rescript-x/src/Htmx.js");
let Stdlib_Exn = require("@rescript/runtime/lib/js/Stdlib_Exn.js");
let HtmxHandler = require("./HtmxHandler.js");
let ErrorMessage = require("./ErrorMessage.js");
let Handlers$ResX = require("rescript-x/src/Handlers.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let SecurityPolicy$ResX = require("rescript-x/src/SecurityPolicy.js");
let FormDataHelpers$ResX = require("rescript-x/src/FormDataHelpers.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

function myVariantFromString(a) {
  if (typeof a === "string") {
    switch (a) {
      case "one" :
        return {
          TAG: "Ok",
          _0: "One"
        };
      case "two" :
        return {
          TAG: "Ok",
          _0: "Two"
        };
    }
  }
  return {
    TAG: "Error",
    _0: `Unknown value: "` + String(a) + `"`
  };
}

let onButtonBlick = Handlers$ResX.hxPost(HtmxHandler.handler, "/button-click", SecurityPolicy$ResX.allow, async param => {
  try {
    let formData = await param.request.formData();
    let firstName = FormDataHelpers$ResX.expectString(formData, "firstName", undefined);
    let lastName = FormDataHelpers$ResX.expectString(formData, "lastName", undefined);
    FormDataHelpers$ResX.expectCustom(formData, "myVariant", myVariantFromString);
    return Hjsx$ResX.Elements.jsx("span", {
      children: "Hi " + firstName + " " + lastName + "!"
    });
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === Stdlib_Exn.$$Error) {
      return Hjsx$ResX.jsx(ErrorMessage.make, {
        message: "Something went wrong..."
      });
    }
    throw exn;
  }
}, undefined);

function Hello(props) {
  return Hjsx$ResX.Elements.jsxs("form", {
    children: [
      Hjsx$ResX.Elements.jsx("button", {
        children: "Hello " + props.name,
        "hx-post": Primitive_option.some(onButtonBlick),
        "hx-swap": Primitive_option.some(Htmx$ResX.Swap.make("innerHTML", "Transition"))
      }),
      Hjsx$ResX.Elements.jsx("input", {
        name: "firstName",
        type: "text",
        value: ""
      }),
      Hjsx$ResX.Elements.jsx("input", {
        name: "lastName",
        type: "text",
        value: ""
      })
    ]
  });
}

let make = Hello;

exports.myVariantFromString = myVariantFromString;
exports.onButtonBlick = onButtonBlick;
exports.make = make;
/* onButtonBlick Not a pure module */
