// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Hjsx$ResX = require("rescript-x/src/Hjsx.js");
var Htmx$ResX = require("rescript-x/src/Htmx.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var HtmxHandler = require("./HtmxHandler.js");
var ErrorMessage = require("./ErrorMessage.js");
var Handlers$ResX = require("rescript-x/src/Handlers.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");
var SecurityPolicy$ResX = require("rescript-x/src/SecurityPolicy.js");
var FormDataHelpers$ResX = require("rescript-x/src/FormDataHelpers.js");

function myVariantFromString(a) {
  if (!(!(a instanceof File) && typeof a !== "string") && typeof a === "string") {
    switch (a) {
      case "one" :
          return {
                  TAG: "Ok",
                  _0: "One"
                };
      case "two" :
          return {
                  TAG: "Ok",
                  _0: "Two"
                };
      default:
        
    }
  }
  return {
          TAG: "Error",
          _0: "Unknown value: \"" + String(a) + "\""
        };
}

var onButtonBlick = Handlers$ResX.hxPost(HtmxHandler.handler, "/button-click", SecurityPolicy$ResX.allow, (async function (param) {
        try {
          var formData = await param.request.formData();
          var firstName = FormDataHelpers$ResX.expectString(formData, "firstName", undefined);
          var lastName = FormDataHelpers$ResX.expectString(formData, "lastName", undefined);
          FormDataHelpers$ResX.expectCustom(formData, "myVariant", myVariantFromString);
          return Hjsx$ResX.Elements.jsx("span", {
                      children: "Hi " + firstName + " " + lastName + "!"
                    });
        }
        catch (raw_exn){
          var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
          if (exn.RE_EXN_ID === Js_exn.$$Error) {
            return Hjsx$ResX.jsx(ErrorMessage.make, {
                        message: "Something went wrong..."
                      });
          }
          throw exn;
        }
      }));

function Hello(props) {
  return Hjsx$ResX.Elements.jsxs("form", {
              children: [
                Hjsx$ResX.Elements.jsx("button", {
                      children: "Hello " + props.name,
                      "hx-post": Caml_option.some(onButtonBlick),
                      "hx-swap": Caml_option.some(Htmx$ResX.Swap.make("innerHTML", "Transition"))
                    }),
                Hjsx$ResX.Elements.jsx("input", {
                      name: "firstName",
                      type: "text",
                      value: ""
                    }),
                Hjsx$ResX.Elements.jsx("input", {
                      name: "lastName",
                      type: "text",
                      value: ""
                    })
              ]
            });
}

var make = Hello;

exports.myVariantFromString = myVariantFromString;
exports.onButtonBlick = onButtonBlick;
exports.make = make;
/* onButtonBlick Not a pure module */
