// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dev$ResX = require("rescript-x/src/Dev.js");
var ResXAssets = require("./__generated__/ResXAssets.js");
var ResX__React$ResX = require("rescript-x/src/ResX__React.js");
var ResX__ReactDOM$ResX = require("rescript-x/src/ResX__ReactDOM.js");

function Html(props) {
  return ResX__ReactDOM$ResX.jsxs("html", {
              children: [
                ResX__ReactDOM$ResX.jsx("head", {
                      children: ResX__ReactDOM$ResX.jsx("link", {
                            href: ResXAssets.assets.styles_css,
                            rel: "stylesheet",
                            type: "text/css"
                          })
                    }),
                ResX__ReactDOM$ResX.jsxs("body", {
                      children: [
                        props.children,
                        ResX__React$ResX.jsx(Dev$ResX.make, {}),
                        ResX__ReactDOM$ResX.jsx("script", {
                              src: "https://unpkg.com/htmx.org@1.9.5"
                            }),
                        ResX__ReactDOM$ResX.jsx("script", {
                              async: true,
                              src: ResXAssets.assets.resXClient_js
                            })
                      ],
                      className: "bg-orange-200 p-10",
                      "hx-boost": true
                    })
              ]
            });
}

var make = Html;

exports.make = make;
/* Dev-ResX Not a pure module */
