// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dev$ResX = require("rescript-x/src/Dev.js");
var Hjsx$ResX = require("rescript-x/src/Hjsx.js");
var ResXAssets = require("./__generated__/ResXAssets.js");

function Html(props) {
  return Hjsx$ResX.Elements.jsxs("html", {
              children: [
                Hjsx$ResX.Elements.jsx("head", {
                      children: Hjsx$ResX.Elements.jsx("link", {
                            href: ResXAssets.assets.styles_css,
                            rel: "stylesheet",
                            type: "text/css"
                          })
                    }),
                Hjsx$ResX.Elements.jsxs("body", {
                      children: [
                        props.children,
                        Hjsx$ResX.jsx(Dev$ResX.make, {}),
                        Hjsx$ResX.Elements.jsx("script", {
                              src: "https://unpkg.com/htmx.org@1.9.5"
                            }),
                        Hjsx$ResX.Elements.jsx("script", {
                              async: true,
                              src: ResXAssets.assets.resXClient_js
                            })
                      ],
                      className: "bg-orange-200 p-10",
                      "hx-boost": true
                    })
              ]
            });
}

var make = Html;

exports.make = make;
/* Dev-ResX Not a pure module */
