// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Handlers$ResX = require("rescript-x/src/Handlers.js");

var handler = Handlers$ResX.make((async function (_request) {
        return {
                userId: undefined
              };
      }), undefined);

function useContext() {
  return Handlers$ResX.useContext(handler);
}

exports.handler = handler;
exports.useContext = useContext;
/* handler Not a pure module */
