// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Handlers$ResX = require("rescript-x/src/Handlers.js");

let handler = Handlers$ResX.make(async _request => ({
  userId: undefined
}), undefined);

function useContext() {
  return Handlers$ResX.useContext(handler);
}

exports.handler = handler;
exports.useContext = useContext;
/* handler Not a pure module */
