// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResX__Handlers = require("res-x/src/ResX__Handlers.js");

var handler = ResX__Handlers.make(async function (_request) {
      return {
              userId: undefined
            };
    });

function useContext() {
  return ResX__Handlers.useContext(handler);
}

exports.handler = handler;
exports.useContext = useContext;
/* handler Not a pure module */
