// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let U = require("./U.js");
let Hjsx$ResX = require("rescript-x/src/Hjsx.js");
let HtmxHandler = require("./HtmxHandler.js");

function Navigation(props) {
  let context = HtmxHandler.useContext();
  let match = context.path;
  let tmp;
  if (match !== 0 && match.hd === "user") {
    let match$1 = match.tl;
    tmp = match$1 !== 0 && match$1.hd === "1" ? "font-bold" : "";
  } else {
    tmp = "";
  }
  return Hjsx$ResX.Elements.jsx("div", {
    children: Hjsx$ResX.Elements.jsx("a", {
      children: "To User 1",
      className: U.tw([
        tmp,
        "underline text-blue-700 visited:text-purple-700"
      ]),
      href: "/user/1",
      "hx-boost": true
    })
  });
}

let make = Navigation;

exports.make = make;
/* Hjsx-ResX Not a pure module */
