// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var U = require("./U.js");
var HtmxHandler = require("./HtmxHandler.js");
var ResX__ReactDOM = require("res-x/src/ResX__ReactDOM.js");

function $$Navigation(props) {
  var context = HtmxHandler.useContext();
  var match = context.path;
  var tmp;
  if (match && match.hd === "user") {
    var match$1 = match.tl;
    tmp = match$1 && match$1.hd === "1" ? "font-bold" : "";
  } else {
    tmp = "";
  }
  return ResX__ReactDOM.jsx("div", {
              children: ResX__ReactDOM.jsx("a", {
                    children: "To User 1",
                    className: U.tw([
                          tmp,
                          "underline text-blue-700 visited:text-purple-700"
                        ]),
                    href: "/user/1",
                    "hx-boost": true
                  })
            });
}

var make = $$Navigation;

exports.make = make;
/* HtmxHandler Not a pure module */
