// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var HtmxHandler = require("./HtmxHandler.js");
var ResX__Utils = require("res-x/src/ResX__Utils.js");
var ResX__ReactDOM = require("res-x/src/ResX__ReactDOM.js");
var ResX__RequestController = require("res-x/src/ResX__RequestController.js");

function SiteMap(props) {
  var context = HtmxHandler.useContext();
  ResX__RequestController.setDocHeader(context.requestController, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
  context.headers.set("Content-Type", "application/xml; charset=UTF-8");
  context.headers.set("Cache-Control", ResX__Utils.CacheControl.make(undefined, "public", [{
              kind: "max-age",
              _0: {
                TAG: "Days",
                _0: 1
              }
            }], undefined, undefined, undefined));
  return ResX__ReactDOM.jsx("urlset", {
              children: ResX__ReactDOM.jsxs("url", {
                    children: [
                      ResX__ReactDOM.jsx("loc", {
                            children: "https://www.example.com/"
                          }),
                      ResX__ReactDOM.jsx("lastmod", {
                            children: "2023-10-15"
                          }),
                      ResX__ReactDOM.jsx("changefreq", {
                            children: "weekly"
                          }),
                      ResX__ReactDOM.jsx("priority", {
                            children: "1.0"
                          })
                    ]
                  }),
              xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9"
            });
}

console.log(ResX__Utils.CacheControl.make(undefined, "public", [{
            kind: "max-age",
            _0: {
              TAG: "Days",
              _0: 1
            }
          }], undefined, undefined, undefined));

var make = SiteMap;

exports.make = make;
/*  Not a pure module */
