// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Hjsx$ResX = require("rescript-x/src/Hjsx.js");
var Utils$ResX = require("rescript-x/src/Utils.js");
var HtmxHandler = require("./HtmxHandler.js");
var RequestController$ResX = require("rescript-x/src/RequestController.js");

function SiteMap(props) {
  var context = HtmxHandler.useContext();
  RequestController$ResX.setDocHeader(context.requestController, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
  context.headers.set("Content-Type", "application/xml; charset=UTF-8");
  context.headers.set("Cache-Control", Utils$ResX.CacheControl.make(undefined, "public", [{
              kind: "max-age",
              _0: {
                TAG: "Days",
                _0: 1
              }
            }], undefined, undefined, undefined));
  return Hjsx$ResX.Elements.jsx("urlset", {
              children: Hjsx$ResX.Elements.jsxs("url", {
                    children: [
                      Hjsx$ResX.Elements.jsx("loc", {
                            children: "https://www.example.com/"
                          }),
                      Hjsx$ResX.Elements.jsx("lastmod", {
                            children: "2023-10-15"
                          }),
                      Hjsx$ResX.Elements.jsx("changefreq", {
                            children: "weekly"
                          }),
                      Hjsx$ResX.Elements.jsx("priority", {
                            children: "1.0"
                          })
                    ]
                  }),
              xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9"
            });
}

var make = SiteMap;

exports.make = make;
/* Hjsx-ResX Not a pure module */
