// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var BunUtils$ResX = require("rescript-x/src/BunUtils.js");

function wait() {
  return new Promise((function (resolve, param) {
                setTimeout((function () {
                        resolve();
                      }), 2000);
              }));
}

var server = Bun.serve({
      development: BunUtils$ResX.isDev,
      port: 5555,
      fetch: (async function (_request, _server) {
          var match = new TransformStream({
                transform: (function (chunk, controller) {
                    controller.enqueue(chunk);
                  })
              });
          var writer = match.writable.getWriter();
          var textEncoder = new TextEncoder();
          writer.write(textEncoder.encode("Hello!"));
          writer.close();
          var response = new Response(match.readable);
          response.headers.set("Content-Type", "text/html");
          return response;
        })
    });

var port = 5555;

exports.port = port;
exports.wait = wait;
exports.server = server;
/* server Not a pure module */
