// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let BunUtils$ResX = require("rescript-x/src/BunUtils.js");

function wait() {
  return new Promise((resolve, param) => {
    setTimeout(() => resolve(), 2000);
  });
}

let server = Bun.serve({
  development: BunUtils$ResX.isDev,
  port: 5555,
  fetch: async (_request, _server) => {
    let match = new TransformStream({
      transform: (chunk, controller) => {
        controller.enqueue(chunk);
      }
    });
    let writer = match.writable.getWriter();
    let textEncoder = new TextEncoder();
    writer.write(textEncoder.encode("Hello!"));
    writer.close();
    let response = new Response(match.readable);
    response.headers.set("Content-Type", "text/html");
    return response;
  }
});

let port = 5555;

exports.port = port;
exports.wait = wait;
exports.server = server;
/* server Not a pure module */
