// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function tw(classes) {
  return classes.filter(function (c) {
                return c !== "";
              }).join(" ");
}

exports.tw = tw;
/* No side effect */
