// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Hjsx$ResX = require("rescript-x/src/Hjsx.js");

function UserFriends(props) {
  return Hjsx$ResX.Elements.jsx("div", {});
}

var make = UserFriends;

exports.make = make;
/* Hjsx-ResX Not a pure module */
