// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResX__ReactDOM$ResX = require("rescript-x/src/ResX__ReactDOM.js");

function UserFriends(props) {
  return ResX__ReactDOM$ResX.jsx("div", {});
}

var make = UserFriends;

exports.make = make;
/* ResX__ReactDOM-ResX Not a pure module */
