// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var UserPage = require("./UserPage.js");
var FourOhFour = require("./FourOhFour.js");
var UserFriends = require("./UserFriends.js");
var ResX__React$ResX = require("rescript-x/src/ResX__React.js");
var RequestController$ResX = require("rescript-x/src/RequestController.js");

function match(userRoutes, headers, requestController) {
  RequestController$ResX.appendTitleSegment(requestController, "Users");
  if (userRoutes) {
    var userRoutes$1 = userRoutes.tl;
    var userId = userRoutes.hd;
    RequestController$ResX.appendTitleSegment(requestController, userId);
    headers.set("Cache-Control", "private");
    var tmp;
    tmp = userRoutes$1 && userRoutes$1.hd === "friends" && !userRoutes$1.tl ? ResX__React$ResX.jsx(UserFriends.make, {
            userId: userId
          }) : null;
    return ResX__React$ResX.jsx(UserPage.make, {
                innerContent: tmp,
                userId: userId
              });
  }
  RequestController$ResX.appendTitleSegment(requestController, "Not found");
  return ResX__React$ResX.jsx(FourOhFour.make, {});
}

exports.match = match;
/* UserPage Not a pure module */
