// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResX__ReactDOM = require("res-x/src/ResX__ReactDOM.js");

function UserFriends(props) {
  return ResX__ReactDOM.jsx("div", {});
}

var make = UserFriends;

exports.make = make;
/* ResX__ReactDOM Not a pure module */
