// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Hjsx$ResX = require("rescript-x/src/Hjsx.js");
let Htmx$ResX = require("rescript-x/src/Htmx.js");
let ResXAssets = require("./__generated__/ResXAssets.js");
let Stdlib_Exn = require("@rescript/runtime/lib/js/Stdlib_Exn.js");
let Client$ResX = require("rescript-x/src/Client.js");
let HtmxHandler = require("./HtmxHandler.js");
let Stdlib_JsExn = require("@rescript/runtime/lib/js/Stdlib_JsExn.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let FailingComponent = require("./FailingComponent.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let ErrorBoundary$ResX = require("rescript-x/src/ErrorBoundary.js");
let SecurityPolicy$ResX = require("rescript-x/src/SecurityPolicy.js");
let FormDataHelpers$ResX = require("rescript-x/src/FormDataHelpers.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

let onForm = HtmxHandler.handler.hxPost("/user-single", SecurityPolicy$ResX.allow, async param => {
  let formData = await param.request.formData();
  try {
    let name = FormDataHelpers$ResX.expectString(formData, "name", undefined);
    let active = FormDataHelpers$ResX.expectCheckbox(formData, "active");
    return Hjsx$ResX.Elements.jsx("div", {
      children: `Some user ` + name + ` is ` + (
        active ? "active" : "not active"
      )
    });
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    if (err.RE_EXN_ID === Stdlib_Exn.$$Error) {
      console.error(err._1);
      return Hjsx$ResX.Elements.jsx("div", {
        children: "Failed"
      });
    }
    throw err;
  }
}, undefined);

function UserPage(props) {
  let ctx = HtmxHandler.useContext();
  ctx.headers.set("Content-Type", "text/html");
  return Hjsx$ResX.Elements.jsxs("div", {
    children: [
      Hjsx$ResX.Elements.jsxs("form", {
        children: [
          Hjsx$ResX.Elements.jsx("img", {
            src: ResXAssets.assets.images__test_img_jpeg
          }),
          Hjsx$ResX.Elements.jsx("div", {
            children: Hjsx$ResX.Elements.jsx("div", {
              children: `User 123 3333 ` + props.userId,
              className: "text-2xl bg-slate-200 text-gray-500"
            }),
            id: "user-single"
          }),
          Hjsx$ResX.Elements.jsx("div", {
            children: Hjsx$ResX.Elements.jsx("input", {
              className: "p-2",
              name: "name",
              type: "text"
            }),
            className: "p-2"
          }),
          Hjsx$ResX.Elements.jsx("div", {
            children: Hjsx$ResX.Elements.jsx("input", {
              className: "invalid:border-green-400 border border-gray-500",
              name: "lastName",
              required: true,
              type: "text",
              "resx-validity-message": Primitive_option.some(Client$ResX.ValidityMessage.make({
                valueMissing: "Yo, you need to fill this in!"
              }))
            }),
            className: "p-2"
          }),
          Hjsx$ResX.Elements.jsx("div", {
            children: Hjsx$ResX.Elements.jsx("input", {
              name: "active",
              type: "checkbox"
            }),
            className: "p-2"
          }),
          Hjsx$ResX.Elements.jsxs("div", {
            children: [
              Hjsx$ResX.Elements.jsxs("label", {
                children: [
                  Hjsx$ResX.Elements.jsx("input", {
                    name: "status",
                    type: "radio",
                    value: "on"
                  }),
                  "On"
                ]
              }),
              Hjsx$ResX.Elements.jsxs("label", {
                children: [
                  Hjsx$ResX.Elements.jsx("input", {
                    name: "status",
                    type: "radio",
                    value: "off"
                  }),
                  "Off"
                ]
              })
            ],
            className: "p-2"
          }),
          Hjsx$ResX.Elements.jsx("div", {
            children: Hjsx$ResX.Elements.jsx("textarea", {
              name: "description"
            }),
            className: "p-2"
          }),
          Hjsx$ResX.Elements.jsx("div", {
            children: Hjsx$ResX.Elements.jsx("button", {
              children: "Submit form",
              id: "test",
              "resx-onclick": Primitive_option.some(Client$ResX.Actions.make([{
                  kind: "ToggleClass",
                  target: "This",
                  className: "text-xl"
                }]))
            }),
            className: "p-2"
          }),
          Hjsx$ResX.jsx(ErrorBoundary$ResX.make, {
            children: Hjsx$ResX.jsx(FailingComponent.make, {}),
            renderError: err => Hjsx$ResX.Elements.jsx("div", {
              children: "Oops, failed! " + Stdlib_Option.getOr(Stdlib_JsExn.message(err), "-")
            })
          })
        ],
        "hx-post": Primitive_option.some(onForm),
        "hx-swap": Primitive_option.some(Htmx$ResX.Swap.make("innerHTML", undefined)),
        "hx-target": Primitive_option.some(Htmx$ResX.Target.make({
          TAG: "CssSelector",
          _0: "#user-single"
        }))
      }),
      props.innerContent
    ],
    className: "p-8"
  });
}

let make = UserPage;

exports.onForm = onForm;
exports.make = make;
/* onForm Not a pure module */
