// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let $$Bun = require("bun");
let Nodefs = require("node:fs");
let Process = require("process");
let Nodepath = require("node:path");
let Nodecrypto = require("node:crypto");
let Nodemodule = require("node:module");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let Primitive_string = require("@rescript/runtime/lib/js/Primitive_string.js");
let Promises = require("node:fs/promises");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

let jsEntryExtensions = [
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".mjs",
  ".cjs"
];

let cssEntryExtension = ".css";

let devOutputDir = Nodepath.join(".resx", "dev");

let prodOutputDir = "dist";

let generatedDir = Nodepath.join("src", "__generated__");

let generatedResFile = Nodepath.join(generatedDir, "ResXAssets.res");

let generatedJsFile = Nodepath.join(generatedDir, "res-x-assets.js");

let manifestFile = "resx-assets.json";

let resXClientKey = "resXClient_js";

let resXClientOutput = "resx-client.js";

function makeResXUsageError(message) {
  let error = new Error(message);
  error.name = "ResXUsageError";
  error.code = "RESX_USAGE";
  return error;
}

function makeResXBuildError(message) {
  let error = new Error(message);
  error.name = "ResXBuildError";
  error.code = "RESX_BUILD";
  return error;
}

function throwJsError(error) {
  throw {
    RE_EXN_ID: "JsExn",
    _1: error,
    Error: new Error()
  };
}

function isNullish(value) {
  return value == null;
}

function boolFromAny(value) {
  return value;
}

function tryOrNone(f) {
  let value;
  try {
    value = f();
  } catch (exn) {
    return;
  }
  return Primitive_option.some(value);
}

async function tryOrNoneAsync(f) {
  let value;
  try {
    value = await f();
  } catch (exn) {
    return;
  }
  return Primitive_option.some(value);
}

function isJsFunction(value) {
  return typeof value === "function";
}

function isJsBoolean(value) {
  return typeof value === "boolean";
}

function isJsString(value) {
  return typeof value === "string";
}

function isJsObject(value) {
  return typeof value === "object";
}

function toPosixPath(value) {
  if (Nodepath.sep === "/") {
    return value;
  } else {
    return value.split(Nodepath.sep).join("/");
  }
}

function isPathInside(candidatePath, basePath) {
  let relative = Nodepath.relative(basePath, candidatePath);
  if (relative === "") {
    return true;
  } else if (relative.startsWith("..")) {
    return false;
  } else {
    return !Nodepath.isAbsolute(relative);
  }
}

async function pathExists(targetPath) {
  try {
    await Nodefs.promises.access(targetPath);
    return true;
  } catch (exn) {
    return false;
  }
}

function pathExistsSync(targetPath) {
  return Nodefs.existsSync(targetPath);
}

function sha256HexBuffer(input) {
  let hash = Nodecrypto.createHash("sha256");
  hash.update(input);
  return hash.digest().toString("hex");
}

function sha256HexString(input) {
  return sha256HexBuffer(Buffer.from(input));
}

function hash8Buffer(input) {
  return sha256HexBuffer(input).slice(0, 8);
}

function ensureTrailingSlash(value) {
  if (value.endsWith("/")) {
    return value;
  } else {
    return value + `/`;
  }
}

async function writeIfChangedBuffer(filePath, content) {
  let previous;
  let exit = 0;
  let bytes;
  try {
    bytes = await Promises.readFile(filePath);
    exit = 1;
  } catch (exn) {
    previous = undefined;
  }
  if (exit === 1) {
    previous = bytes;
  }
  if (previous !== undefined && Buffer.compare(previous, content) === 0) {
    return false;
  }
  await Nodefs.promises.mkdir(Nodepath.dirname(filePath), {
    recursive: true
  });
  await Promises.writeFile(filePath, content);
  return true;
}

async function writeIfChangedString(filePath, content) {
  let bytes = Buffer.from(content);
  await writeIfChangedBuffer(filePath, bytes);
}

function isAsciiLower(code) {
  if (code >= 97) {
    return code <= 122;
  } else {
    return false;
  }
}

function isAsciiUpper(code) {
  if (code >= 65) {
    return code <= 90;
  } else {
    return false;
  }
}

function isAsciiDigit(code) {
  if (code >= 48) {
    return code <= 57;
  } else {
    return false;
  }
}

function sanitizeFieldChars(input) {
  let chars = Array.from(input);
  let sanitized = chars.map(char => {
    if (char === "_") {
      return "_";
    }
    let code = char.charCodeAt(0);
    if (isAsciiLower(code) || isAsciiUpper(code) || isAsciiDigit(code)) {
      return char;
    } else {
      return "_";
    }
  });
  return sanitized.join("");
}

function toRescriptFieldName(fieldName, existing) {
  let slashNormalized = fieldName.split("/").join("__");
  let transformedRef = sanitizeFieldChars(slashNormalized);
  if (transformedRef === "") {
    transformedRef = "a";
  } else {
    let first = transformedRef.slice(0, 1);
    let code = first.charCodeAt(0);
    if (!isAsciiLower(code)) {
      transformedRef = `a` + transformedRef;
    }
  }
  while (existing.has(transformedRef)) {
    transformedRef = transformedRef + `_`;
  };
  return transformedRef;
}

let jsEntryExtensionSet = new Set(jsEntryExtensions);

function formatBunLogs(logs, projectRoot) {
  if (logs.length === 0) {
    return "";
  }
  let messages = logs.map(log => {
    let match;
    match = log.name === "BuildMessage" ? [
        log.message,
        Primitive_option.fromNull(log.position)
      ] : [
        log.message,
        Primitive_option.fromNull(log.position)
      ];
    let position = match[1];
    let rawMessage = match[0];
    let message = rawMessage !== "" ? rawMessage : "Unknown build error";
    if (position === undefined) {
      return message;
    }
    let filePath = position.file;
    let relative = isPathInside(filePath, projectRoot) ? toPosixPath(Nodepath.relative(projectRoot, filePath)) : filePath;
    let line = position.line.toString();
    let column = position.column.toString();
    return relative + `:` + line + `:` + column + ` ` + message;
  });
  return messages.join("\n");
}

function normalizeRootInput(root) {
  if (root !== undefined && root !== "") {
    return root;
  } else {
    return Process.cwd();
  }
}

function scanGlobPaths(pattern, cwd, dot) {
  let glob = new $$Bun.Glob(pattern);
  let iter = glob.scanSync({
    cwd: cwd,
    dot: dot,
    followSymlinks: false,
    onlyFiles: true
  });
  return Array.from(iter).map(toPosixPath);
}

function scanGlobPatternsUniqueSorted(patterns, cwd, dot) {
  let seen = new Set();
  let results = [];
  for (let i = 0, i_finish = patterns.length; i < i_finish; ++i) {
    let pattern = patterns[i];
    let scanned = scanGlobPaths(pattern, cwd, dot);
    for (let j = 0, j_finish = scanned.length; j < j_finish; ++j) {
      let relPath = scanned[j];
      if (!seen.has(relPath)) {
        seen.add(relPath);
        results.push(relPath);
      }
    }
  }
  results.sort(Primitive_string.compare);
  return results;
}

async function resolveProjectRoot(root) {
  let rootInput = normalizeRootInput(root);
  let absolute = Nodepath.resolve(rootInput);
  if (!await pathExists(absolute)) {
    let error = makeResXBuildError(`Project root not found: ` + absolute);
    throw {
      RE_EXN_ID: "JsExn",
      _1: error,
      Error: new Error()
    };
  }
  let stats = await Promises.stat(absolute);
  if (!stats.isDirectory()) {
    let error$1 = makeResXBuildError(`Project root is not a directory: ` + absolute);
    throw {
      RE_EXN_ID: "JsExn",
      _1: error$1,
      Error: new Error()
    };
  }
  return await Promises.realpath(absolute);
}

function resolveClientSource() {
  return Nodepath.resolve(__dirname, "ResXClient.js");
}

async function discoverManagedFiles(projectRoot, directoryName) {
  let baseDir = Nodepath.join(projectRoot, directoryName);
  if (!await pathExists(baseDir)) {
    return [];
  }
  let projectRootReal = await Promises.realpath(projectRoot);
  let sortedRelPaths = scanGlobPatternsUniqueSorted(["**/*"], baseDir, false);
  let files = [];
  for (let i = 0, i_finish = sortedRelPaths.length; i < i_finish; ++i) {
    let relPath = sortedRelPaths[i];
    let absPath = Nodepath.join(baseDir, relPath);
    let exit = 0;
    let realPath;
    try {
      realPath = await Promises.realpath(absPath);
      exit = 1;
    } catch (exn) {
      
    }
    if (exit === 1) {
      if (isPathInside(realPath, projectRootReal)) {
        files.push({
          relPath: relPath,
          absPath: absPath,
          realPath: realPath
        });
      }
    }
  }
  return files;
}

function hasJsEntryExtension(extension) {
  return jsEntryExtensionSet.has(extension.toLowerCase());
}

function classifyAssetFiles(assetFiles) {
  let jsEntries = [];
  let cssEntries = [];
  let copiedAssets = [];
  for (let i = 0, i_finish = assetFiles.length; i < i_finish; ++i) {
    let file = assetFiles[i];
    let extension = Nodepath.extname(file.relPath).toLowerCase();
    if (jsEntryExtensionSet.has(extension.toLowerCase())) {
      jsEntries.push(file);
    } else if (extension === cssEntryExtension) {
      cssEntries.push(file);
    } else {
      copiedAssets.push(file);
    }
  }
  return {
    jsEntries: jsEntries,
    cssEntries: cssEntries,
    copiedAssets: copiedAssets
  };
}

function jsOutputRelativePath(sourceRelPath) {
  let parsed = Nodepath.posix.parse(sourceRelPath);
  let name = parsed.name + `.js`;
  if (parsed.dir !== "") {
    return parsed.dir + `/` + name;
  } else {
    return name;
  }
}

function hashedRelativePath(relPath, bytes) {
  let parsed = Nodepath.posix.parse(relPath);
  let name = parsed.name + `-` + hash8Buffer(bytes) + parsed.ext;
  if (parsed.dir !== "") {
    return parsed.dir + `/` + name;
  } else {
    return name;
  }
}

function extractLogs(result) {
  return result.logs;
}

async function runBunBuild(entryPath, minify) {
  let result = await tryOrNoneAsync(() => Bun.build({
    entrypoints: [entryPath],
    target: "browser",
    format: "esm",
    splitting: false,
    sourcemap: "none",
    minify: minify
  }));
  if (result === undefined) {
    return {
      ok: false,
      logs: [],
      bytes: undefined
    };
  }
  if (!result.success) {
    return {
      ok: false,
      logs: result.logs,
      bytes: undefined
    };
  }
  let outputs = result.outputs;
  if (outputs.length === 0) {
    return {
      ok: false,
      logs: [],
      bytes: undefined
    };
  }
  let value = outputs.find(output => output.kind === "entry-point");
  let primary = value !== undefined ? value : outputs[0];
  let rawBytes = await primary.arrayBuffer();
  let bytes = Buffer.from(rawBytes);
  return {
    ok: true,
    logs: result.logs,
    bytes: bytes
  };
}

function createRootRequire(projectRoot) {
  let packageJson = Nodepath.join(projectRoot, "package.json");
  if (Nodefs.existsSync(packageJson)) {
    return Nodemodule.createRequire(packageJson);
  } else {
    return Nodemodule.createRequire(Nodepath.join(projectRoot, "index.js"));
  }
}

async function maybeTransformCssWithPostcss(entryPath, projectRoot) {
  let configCandidates = [
    Nodepath.join(projectRoot, "postcss.config.js"),
    Nodepath.join(projectRoot, "postcss.config.cjs")
  ];
  let configPathRef;
  for (let i = 0, i_finish = configCandidates.length; i < i_finish; ++i) {
    if (configPathRef === undefined) {
      let candidate = configCandidates[i];
      if (await pathExists(candidate)) {
        configPathRef = candidate;
      }
    }
  }
  let configPath = configPathRef;
  if (configPath === undefined) {
    return;
  }
  let rootRequire = tryOrNone(() => createRootRequire(projectRoot));
  if (rootRequire === undefined) {
    return;
  }
  let value = tryOrNone(() => rootRequire("postcss"));
  let postcssFactory = value !== undefined ? Primitive_option.valFromOption(value) : undefined;
  if (postcssFactory === undefined) {
    return;
  }
  let configValue = tryOrNone(() => rootRequire(configPath));
  if (configValue === undefined) {
    return;
  }
  let initialConfig = Primitive_option.valFromOption(configValue);
  let config = typeof initialConfig === "function" ? tryOrNone(() => initialConfig({
      env: "development"
    })) : Primitive_option.some(initialConfig);
  if (config === undefined) {
    return;
  }
  let plugins = [];
  let configuredPlugins = Primitive_option.valFromOption(config).plugins;
  if (!(configuredPlugins == null)) {
    if (Array.isArray(configuredPlugins)) {
      for (let i$1 = 0, i_finish$1 = configuredPlugins.length; i$1 < i_finish$1; ++i$1) {
        let pluginEntry = configuredPlugins[i$1];
        if (!isNullish(pluginEntry) && pluginEntry !== false) {
          if (typeof pluginEntry === "function") {
            plugins.push(pluginEntry);
          } else if (typeof pluginEntry === "string") {
            let exit = 0;
            let loaded;
            try {
              loaded = rootRequire(pluginEntry);
              exit = 1;
            } catch (exn) {
              
            }
            if (exit === 1) {
              if (typeof loaded === "function") {
                plugins.push(loaded());
              } else {
                plugins.push(loaded);
              }
            }
          } else if (Array.isArray(pluginEntry)) {
            let nameAny = pluginEntry[0];
            if (nameAny !== undefined) {
              let nameAny$1 = Primitive_option.valFromOption(nameAny);
              if (typeof nameAny$1 === "string") {
                let exit$1 = 0;
                let loaded$1;
                try {
                  loaded$1 = rootRequire(nameAny$1);
                  exit$1 = 1;
                } catch (exn$1) {
                  
                }
                if (exit$1 === 1) {
                  if (typeof loaded$1 === "function") {
                    let options = pluginEntry[1];
                    if (options !== undefined) {
                      plugins.push(loaded$1(Primitive_option.valFromOption(options)));
                    } else {
                      plugins.push(loaded$1());
                    }
                  } else {
                    plugins.push(loaded$1);
                  }
                }
              } else {
                plugins.push(pluginEntry);
              }
            } else {
              plugins.push(pluginEntry);
            }
          } else {
            plugins.push(pluginEntry);
          }
        }
      }
    } else if (typeof configuredPlugins === "object") {
      let configuredPluginEntries = Object.entries(configuredPlugins);
      for (let i$2 = 0, i_finish$2 = configuredPluginEntries.length; i$2 < i_finish$2; ++i$2) {
        let match = configuredPluginEntries[i$2];
        let pluginOptions = match[1];
        if (pluginOptions !== false) {
          let exit$2 = 0;
          let loaded$2;
          try {
            loaded$2 = rootRequire(match[0]);
            exit$2 = 1;
          } catch (exn$2) {
            
          }
          if (exit$2 === 1) {
            if (typeof loaded$2 === "function") {
              if (isNullish(pluginOptions) || pluginOptions === true) {
                plugins.push(loaded$2());
              } else {
                plugins.push(loaded$2(pluginOptions));
              }
            } else {
              plugins.push(loaded$2);
            }
          }
        }
      }
    }
  }
  if (plugins.length === 0) {
    return;
  }
  let source = await Promises.readFile(entryPath, {
    encoding: "utf8"
  });
  let transformed;
  try {
    let processor = postcssFactory(plugins);
    transformed = await processor.process(source, {
      from: entryPath,
      to: entryPath,
      map: false
    });
  } catch (exn$3) {
    return;
  }
  return Buffer.from(transformed.css);
}

async function buildJavaScript(entryPath, projectRoot, mode) {
  let built = await runBunBuild(entryPath, mode === "prod");
  if (built.ok) {
    let bytes = built.bytes;
    if (bytes !== undefined) {
      return bytes;
    }
    let error = makeResXBuildError(`JavaScript build failed: ` + entryPath);
    throw {
      RE_EXN_ID: "JsExn",
      _1: error,
      Error: new Error()
    };
  }
  let details = formatBunLogs(built.logs, projectRoot);
  let error$1 = makeResXBuildError(details !== "" ? details : `JavaScript build failed: ` + entryPath);
  throw {
    RE_EXN_ID: "JsExn",
    _1: error$1,
    Error: new Error()
  };
}

async function buildCss(entryPath, projectRoot, mode) {
  let built = await runBunBuild(entryPath, mode === "prod");
  let transformed = await maybeTransformCssWithPostcss(entryPath, projectRoot);
  if (transformed !== undefined) {
    return transformed;
  }
  if (built.ok) {
    let bytes = built.bytes;
    if (bytes !== undefined) {
      return bytes;
    }
    let error = makeResXBuildError(`CSS build failed: ` + entryPath);
    throw {
      RE_EXN_ID: "JsExn",
      _1: error,
      Error: new Error()
    };
  }
  let details = formatBunLogs(built.logs, projectRoot);
  let error$1 = makeResXBuildError(details !== "" ? details : `CSS build failed: ` + entryPath);
  throw {
    RE_EXN_ID: "JsExn",
    _1: error$1,
    Error: new Error()
  };
}

async function emitManagedAsset(mode, outputAssetsDir, logicalRelPath, bytes) {
  let outputRelPath = mode === "prod" ? hashedRelativePath(logicalRelPath, bytes) : logicalRelPath;
  let normalizedRelPath = toPosixPath(outputRelPath);
  let destination = Nodepath.join(outputAssetsDir, normalizedRelPath);
  await Nodefs.promises.mkdir(Nodepath.dirname(destination), {
    recursive: true
  });
  await Promises.writeFile(destination, bytes);
  return {
    outputRelPath: normalizedRelPath,
    outputPath: destination,
    urlPath: `/` + toPosixPath(Nodepath.posix.join("assets", normalizedRelPath)),
    contentHash: sha256HexBuffer(bytes)
  };
}

async function copyPublicFiles(publicFiles, projectRoot, outputRoot) {
  let copied = [];
  for (let i = 0, i_finish = publicFiles.length; i < i_finish; ++i) {
    let file = publicFiles[i];
    let destination = Nodepath.join(outputRoot, file.relPath);
    if (isPathInside(destination, outputRoot)) {
      await Nodefs.promises.mkdir(Nodepath.dirname(destination), {
        recursive: true
      });
      await Nodefs.promises.copyFile(file.absPath, destination);
      let bytes = await Promises.readFile(destination);
      copied.push({
        relPath: file.relPath,
        outputPath: destination,
        contentHash: sha256HexBuffer(bytes)
      });
    }
  }
  return copied;
}

function buildGeneratedJs(keyedRecords) {
  let lines = keyedRecords.map(record => `  ` + record.key + `: ` + JSON.stringify(record.urlPath) + `,`);
  return `export const assets = {\n` + lines.join("\n") + `\n};\n`;
}

function buildGeneratedRes(keyedRecords, sourceByKey) {
  let lines = [];
  lines.push("// Generated by ResX, do not edit manually");
  lines.push("");
  lines.push("type assets = {");
  lines.push("  /** ResX Client Bundle */");
  lines.push("  resXClient_js: string,");
  for (let i = 0, i_finish = keyedRecords.length; i < i_finish; ++i) {
    let record = keyedRecords[i];
    if (record.key !== resXClientKey) {
      let value = sourceByKey[record.key];
      let source = value !== undefined ? value : record.key;
      let escapedSource = source.split("`").join("\\`");
      lines.push("");
      lines.push(`  /** \`` + escapedSource + `\` */`);
      lines.push(`  ` + record.key + `: string,`);
    }
  }
  lines.push("}");
  lines.push("");
  lines.push("@module(\"./res-x-assets.js\") external assets: assets = \"assets\"");
  lines.push("");
  return lines.join("\n");
}

function buildManifest(mode, keyedRecords) {
  let seedParts = keyedRecords.map(record => record.key + `|` + record.urlPath + `|` + record.contentHash);
  let input = seedParts.join("\n");
  let fingerprint = sha256HexBuffer(Buffer.from(input));
  let assetsLines = [];
  for (let i = 0, i_finish = keyedRecords.length; i < i_finish; ++i) {
    let record = keyedRecords[i];
    let comma = i < (keyedRecords.length - 1 | 0) ? "," : "";
    assetsLines.push(`    ` + JSON.stringify(record.key) + `: ` + JSON.stringify(record.urlPath) + comma);
  }
  let assetsBody = assetsLines.length === 0 ? "{}" : `{
` + assetsLines.join("\n") + `
  }`;
  return `{
  "version": 1,
  "mode": ` + JSON.stringify(mode) + `,
  "assets": ` + assetsBody + `,
  "fingerprint": ` + JSON.stringify(fingerprint) + `
}
`;
}

async function cleanOutputDirectory(outputRoot, projectRoot) {
  if (!isPathInside(outputRoot, projectRoot)) {
    let error = makeResXBuildError(`Refusing to clean outside project root: ` + outputRoot);
    throw {
      RE_EXN_ID: "JsExn",
      _1: error,
      Error: new Error()
    };
  }
  return await Promises.rm(outputRoot, {
    recursive: true,
    force: true
  });
}

async function buildAssets(root, devOpt, cleanOpt) {
  let dev = devOpt !== undefined ? devOpt : false;
  let clean = cleanOpt !== undefined ? cleanOpt : true;
  let mode = dev ? "dev" : "prod";
  let projectRoot = await resolveProjectRoot(root);
  let outputRoot = mode === "dev" ? Nodepath.join(projectRoot, devOutputDir) : Nodepath.join(projectRoot, prodOutputDir);
  let outputAssetsDir = Nodepath.join(outputRoot, "assets");
  if (clean) {
    await cleanOutputDirectory(outputRoot, projectRoot);
  }
  await Nodefs.promises.mkdir(outputAssetsDir, {
    recursive: true
  });
  let assetFiles = await discoverManagedFiles(projectRoot, "assets");
  let publicFiles = await discoverManagedFiles(projectRoot, "public");
  let classified = classifyAssetFiles(assetFiles);
  let managedAssetRecords = [];
  for (let i = 0, i_finish = classified.jsEntries.length; i < i_finish; ++i) {
    let entry = classified.jsEntries[i];
    let bytes = await buildJavaScript(entry.absPath, projectRoot, mode);
    let emitted = await emitManagedAsset(mode, outputAssetsDir, jsOutputRelativePath(entry.relPath), bytes);
    managedAssetRecords.push({
      sourceRelPath: entry.relPath,
      outputRelPath: emitted.outputRelPath,
      outputPath: emitted.outputPath,
      urlPath: emitted.urlPath,
      contentHash: emitted.contentHash
    });
  }
  for (let i$1 = 0, i_finish$1 = classified.cssEntries.length; i$1 < i_finish$1; ++i$1) {
    let entry$1 = classified.cssEntries[i$1];
    let bytes$1 = await buildCss(entry$1.absPath, projectRoot, mode);
    let emitted$1 = await emitManagedAsset(mode, outputAssetsDir, entry$1.relPath, bytes$1);
    managedAssetRecords.push({
      sourceRelPath: entry$1.relPath,
      outputRelPath: emitted$1.outputRelPath,
      outputPath: emitted$1.outputPath,
      urlPath: emitted$1.urlPath,
      contentHash: emitted$1.contentHash
    });
  }
  for (let i$2 = 0, i_finish$2 = classified.copiedAssets.length; i$2 < i_finish$2; ++i$2) {
    let file = classified.copiedAssets[i$2];
    let bytes$2 = await Promises.readFile(file.absPath);
    let emitted$2 = await emitManagedAsset(mode, outputAssetsDir, file.relPath, bytes$2);
    managedAssetRecords.push({
      sourceRelPath: file.relPath,
      outputRelPath: emitted$2.outputRelPath,
      outputPath: emitted$2.outputPath,
      urlPath: emitted$2.urlPath,
      contentHash: emitted$2.contentHash
    });
  }
  managedAssetRecords.sort((a, b) => Primitive_string.compare(a.sourceRelPath, b.sourceRelPath));
  let clientSource = Nodepath.resolve(__dirname, "ResXClient.js");
  let clientBytes = await buildJavaScript(clientSource, projectRoot, mode);
  let emittedClient = await emitManagedAsset(mode, outputAssetsDir, resXClientOutput, clientBytes);
  if (mode === "prod") {
    await copyPublicFiles(publicFiles, projectRoot, outputRoot);
  }
  let usedKeys = new Set();
  usedKeys.add(resXClientKey);
  let sourceByKey = {};
  sourceByKey[resXClientKey] = "resXClient.js";
  let keyedRecords = [{
      key: resXClientKey,
      urlPath: emittedClient.urlPath,
      contentHash: emittedClient.contentHash
    }];
  for (let i$3 = 0, i_finish$3 = managedAssetRecords.length; i$3 < i_finish$3; ++i$3) {
    let record = managedAssetRecords[i$3];
    let key = toRescriptFieldName(record.sourceRelPath, usedKeys);
    usedKeys.add(key);
    sourceByKey[key] = record.sourceRelPath;
    keyedRecords.push({
      key: key,
      urlPath: record.urlPath,
      contentHash: record.contentHash
    });
  }
  keyedRecords.sort((a, b) => Primitive_string.compare(a.key, b.key));
  let generatedResPath = Nodepath.join(projectRoot, generatedResFile);
  let generatedJsPath = Nodepath.join(projectRoot, generatedJsFile);
  await writeIfChangedString(generatedResPath, buildGeneratedRes(keyedRecords, sourceByKey));
  await writeIfChangedString(generatedJsPath, buildGeneratedJs(keyedRecords));
  let manifestPath = Nodepath.join(outputRoot, manifestFile);
  let manifestText = buildManifest(mode, keyedRecords);
  await writeIfChangedString(manifestPath, manifestText);
}

function shouldTriggerSrcRebuild(filename) {
  if (filename === undefined) {
    return false;
  }
  if (filename === "") {
    return false;
  }
  let normalized = toPosixPath(filename);
  if (normalized === "ResXClient.js") {
    return true;
  } else {
    return normalized === "ResXClient.res";
  }
}

function makeDebouncedTask(task, waitMs) {
  let timer = {
    contents: undefined
  };
  let running = {
    contents: false
  };
  let pending = {
    contents: false
  };
  let schedule = () => {
    let existing = timer.contents;
    if (existing !== undefined) {
      clearTimeout(Primitive_option.valFromOption(existing));
    }
    timer.contents = Primitive_option.some(setTimeout(() => {
      timer.contents = undefined;
      runOnce();
    }, waitMs));
  };
  let runOnce = async () => {
    if (running.contents) {
      pending.contents = true;
      return;
    }
    running.contents = true;
    try {
      await task();
    } catch (exn) {
      
    }
    running.contents = false;
    if (pending.contents) {
      pending.contents = false;
      return schedule();
    }
  };
  return schedule;
}

function watchDirectory(targetPath, onChange) {
  if (!Nodefs.existsSync(targetPath)) {
    return;
  }
  let watcher;
  try {
    watcher = Nodefs.watch(targetPath, {
      recursive: true,
      encoding: "utf8"
    }, (_eventType, filename) => onChange(filename));
  } catch (exn) {
    return;
  }
  return Primitive_option.some(watcher);
}

async function startDevWatch(root, cleanOpt, onBuildError) {
  let clean = cleanOpt !== undefined ? cleanOpt : true;
  let projectRoot = await resolveProjectRoot(root);
  let notifyError = onBuildError !== undefined ? onBuildError : param => {};
  let rebuild = makeDebouncedTask(async () => {
    try {
      await buildAssets(projectRoot, true, clean);
      return;
    } catch (raw_error) {
      let error = Primitive_exceptions.internalToException(raw_error);
      if (error.RE_EXN_ID === "JsExn") {
        return notifyError(error._1);
      } else {
        return notifyError(new Error("Unknown build error"));
      }
    }
  }, 120);
  let watchers = [];
  let value = watchDirectory(Nodepath.join(projectRoot, "assets"), param => rebuild());
  if (value !== undefined) {
    watchers.push(Primitive_option.valFromOption(value));
  }
  let value$1 = watchDirectory(Nodepath.join(projectRoot, "public"), param => rebuild());
  if (value$1 !== undefined) {
    watchers.push(Primitive_option.valFromOption(value$1));
  }
  let value$2 = watchDirectory(Nodepath.join(projectRoot, "src"), filename => {
    if (shouldTriggerSrcRebuild(filename)) {
      return rebuild();
    }
  });
  if (value$2 !== undefined) {
    watchers.push(Primitive_option.valFromOption(value$2));
  }
  let watchPatterns = [
    "assets/**/*",
    "public/**/*",
    "src/ResXClient.*"
  ];
  let pollBusy = {
    contents: false
  };
  let computeWatchSignature = async () => {
    let normalized = scanGlobPatternsUniqueSorted(watchPatterns, projectRoot, true);
    let parts = [];
    for (let i = 0, i_finish = normalized.length; i < i_finish; ++i) {
      let relPath = normalized[i];
      let absPath = Nodepath.join(projectRoot, relPath);
      let exit = 0;
      let stats;
      try {
        stats = await Promises.stat(absPath);
        exit = 1;
      } catch (exn) {
        
      }
      if (exit === 1) {
        parts.push(relPath + `:` + stats.size.toString() + `:` + stats.mtimeMs.toString());
      }
    }
    let input = parts.join("\n");
    return sha256HexBuffer(Buffer.from(input));
  };
  let previousSignature = {
    contents: await computeWatchSignature()
  };
  let poller = setInterval(() => {
    if (pollBusy.contents) {
      return;
    } else {
      pollBusy.contents = true;
      (async () => {
        let exit = 0;
        let nextSignature;
        try {
          nextSignature = await computeWatchSignature();
          exit = 1;
        } catch (exn) {
          
        }
        if (exit === 1) {
          if (nextSignature !== previousSignature.contents) {
            previousSignature.contents = nextSignature;
            rebuild();
          }
        }
        pollBusy.contents = false;
      })();
      return;
    }
  }, 500);
  return {
    close: () => {
      clearInterval(poller);
      for (let i = 0, i_finish = watchers.length; i < i_finish; ++i) {
        try {
          watchers[i].close();
        } catch (exn) {
          
        }
      }
    }
  };
}

function closeWatcher(watcher) {
  watcher.close();
}

function decodePathname(pathname) {
  let current = pathname;
  let failed = false;
  for (let _index = 0; _index <= 3; ++_index) {
    if (!failed) {
      let exit = 0;
      let decoded;
      try {
        decoded = decodeURIComponent(current);
        exit = 1;
      } catch (exn) {
        failed = true;
      }
      if (exit === 1 && decoded !== current) {
        current = decoded;
      }
    }
  }
  if (failed) {
    return;
  } else {
    return current;
  }
}

function stripLeadingSlashes(value) {
  let current = value;
  while (current.startsWith("/")) {
    current = current.slice(1);
  };
  return current;
}

function sanitizeUrlPath(pathname) {
  let decoded = decodePathname(pathname);
  if (decoded === undefined) {
    return;
  }
  let normalizedSlashes = decoded.split("\\").join("/");
  let startsWithSlash = normalizedSlashes.startsWith("/");
  let withSlash = startsWithSlash ? normalizedSlashes : `/` + normalizedSlashes;
  let segments = withSlash.split("/");
  let blocked = false;
  for (let i = 0, i_finish = segments.length; i < i_finish; ++i) {
    if (segments[i] === "..") {
      blocked = true;
    }
  }
  if (blocked) {
    return;
  }
  let normalized = Nodepath.posix.normalize(withSlash);
  if (normalized.startsWith("/")) {
    return normalized;
  }
}

function getServeRoots(projectRoot, isDev) {
  if (isDev) {
    return {
      managedAssetsRoot: Nodepath.join(projectRoot, "assets"),
      staticRoot: Nodepath.join(projectRoot, "public")
    };
  } else {
    return {
      managedAssetsRoot: Nodepath.join(Nodepath.join(projectRoot, prodOutputDir), "assets"),
      staticRoot: Nodepath.join(projectRoot, prodOutputDir)
    };
  }
}

async function resolveServedFilePath(baseRoot, relativePath) {
  let relativePosix = stripLeadingSlashes(toPosixPath(relativePath));
  let target = Nodepath.resolve(baseRoot, relativePosix);
  if (!isPathInside(target, baseRoot)) {
    return;
  }
  let exit = 0;
  let stats;
  try {
    stats = await Promises.stat(target);
    exit = 1;
  } catch (exn) {
    return;
  }
  if (exit === 1) {
    if (!stats.isFile()) {
      return;
    }
    let exit$1 = 0;
    let realTarget;
    try {
      realTarget = await Promises.realpath(target);
      exit$1 = 2;
    } catch (exn$1) {
      return;
    }
    if (exit$1 === 2) {
      let exit$2 = 0;
      let realBase;
      try {
        realBase = await Promises.realpath(baseRoot);
        exit$2 = 3;
      } catch (exn$2) {
        return;
      }
      if (exit$2 === 3) {
        if (isPathInside(realTarget, realBase)) {
          return target;
        } else {
          return;
        }
      }
    }
  }
}

function jsSourceCandidatesFromRequest(relativePath) {
  let parsed = Nodepath.posix.parse(relativePath);
  let base = parsed.dir !== "" ? parsed.dir + `/` + parsed.name : parsed.name;
  return jsEntryExtensions.map(ext => base + ext);
}

function responseWithContentType(body, contentType) {
  let headers = new Headers();
  headers.set("Content-Type", contentType);
  return new Response(body, {
    headers: Primitive_option.some(headers)
  });
}

function responseWithStatus(status) {
  return new Response("", {
    status: status
  });
}

function fileResponseFromPath(filePath) {
  return new Response(Bun.file(filePath));
}

function bufferToUtf8String(buffer) {
  return buffer.toString("utf8");
}

function requestUrlPathname(request) {
  return new URL(request.url).pathname;
}

async function resolveDevManagedAssetResponse(projectRoot, managedAssetsRoot, relativePath) {
  let extension = Nodepath.posix.extname(relativePath).toLowerCase();
  if (extension === ".js") {
    let sourcePathRef = await resolveServedFilePath(managedAssetsRoot, relativePath);
    if (sourcePathRef === undefined) {
      let sourceCandidates = jsSourceCandidatesFromRequest(relativePath);
      for (let i = 0, i_finish = sourceCandidates.length; i < i_finish; ++i) {
        if (sourcePathRef === undefined) {
          sourcePathRef = await resolveServedFilePath(managedAssetsRoot, sourceCandidates[i]);
        }
      }
    }
    let sourcePath = sourcePathRef;
    if (sourcePath === undefined) {
      return;
    }
    let jsBytes = await buildJavaScript(sourcePath, projectRoot, "dev");
    return responseWithContentType(jsBytes.toString("utf8"), "text/javascript; charset=utf-8");
  }
  if (extension === ".css") {
    let sourcePath$1 = await resolveServedFilePath(managedAssetsRoot, relativePath);
    if (sourcePath$1 === undefined) {
      return;
    }
    let cssBytes = await buildCss(sourcePath$1, projectRoot, "dev");
    return responseWithContentType(cssBytes.toString("utf8"), "text/css; charset=utf-8");
  }
  let exactPath = await resolveServedFilePath(managedAssetsRoot, relativePath);
  if (exactPath !== undefined) {
    return new Response(Bun.file(exactPath));
  }
}

let suspiciousRootNames = [
  "bin",
  "etc",
  "home",
  "opt",
  "private",
  "proc",
  "root",
  "sbin",
  "sys",
  "tmp",
  "usr",
  "var",
  "windows"
];

function hasSuspiciousRoot(value) {
  return suspiciousRootNames.includes(value);
}

async function serveStaticFileFromBuild(request, projectRoot, isDev) {
  let pathname = new URL(request.url).pathname;
  let sanitized = sanitizeUrlPath(pathname);
  if (sanitized === undefined) {
    return responseWithStatus(403);
  }
  let segments = sanitized.split("/");
  let value = segments.find(segment => segment !== "");
  let firstSegment = value !== undefined ? value : "";
  if (suspiciousRootNames.includes(firstSegment)) {
    return responseWithStatus(403);
  }
  if (firstSegment === "src") {
    let sourceRelative = sanitized.slice(1);
    let sourceCandidate = Nodepath.resolve(projectRoot, sourceRelative);
    if (isPathInside(sourceCandidate, projectRoot) && Nodefs.existsSync(sourceCandidate)) {
      return responseWithStatus(403);
    } else {
      return;
    }
  }
  if (sanitized === "/") {
    return;
  }
  let roots = getServeRoots(projectRoot, isDev);
  let managedAssetsRequest = sanitized === "/assets" || sanitized.startsWith("/assets/");
  if (managedAssetsRequest) {
    let relative = sanitized === "/assets" ? "" : sanitized.slice(8);
    if (isDev) {
      let response;
      try {
        response = await resolveDevManagedAssetResponse(projectRoot, roots.managedAssetsRoot, relative);
      } catch (raw_exn) {
        let exn = Primitive_exceptions.internalToException(raw_exn);
        console.error(`[resx] failed to serve dev asset /assets/` + relative + `\n` + String(exn));
        return responseWithStatus(500);
      }
      if (response !== undefined) {
        return response;
      } else {
        return responseWithStatus(404);
      }
    }
    let filePath = await resolveServedFilePath(roots.managedAssetsRoot, relative);
    if (filePath !== undefined) {
      return new Response(Bun.file(filePath));
    } else {
      return responseWithStatus(404);
    }
  }
  let relative$1 = sanitized.slice(1);
  let filePath$1 = await resolveServedFilePath(roots.staticRoot, relative$1);
  if (filePath$1 !== undefined) {
    return new Response(Bun.file(filePath$1));
  }
}

exports.jsEntryExtensions = jsEntryExtensions;
exports.cssEntryExtension = cssEntryExtension;
exports.devOutputDir = devOutputDir;
exports.prodOutputDir = prodOutputDir;
exports.generatedDir = generatedDir;
exports.generatedResFile = generatedResFile;
exports.generatedJsFile = generatedJsFile;
exports.manifestFile = manifestFile;
exports.resXClientKey = resXClientKey;
exports.resXClientOutput = resXClientOutput;
exports.makeResXUsageError = makeResXUsageError;
exports.makeResXBuildError = makeResXBuildError;
exports.throwJsError = throwJsError;
exports.isNullish = isNullish;
exports.boolFromAny = boolFromAny;
exports.tryOrNone = tryOrNone;
exports.tryOrNoneAsync = tryOrNoneAsync;
exports.isJsFunction = isJsFunction;
exports.isJsBoolean = isJsBoolean;
exports.isJsString = isJsString;
exports.isJsObject = isJsObject;
exports.toPosixPath = toPosixPath;
exports.isPathInside = isPathInside;
exports.pathExists = pathExists;
exports.pathExistsSync = pathExistsSync;
exports.sha256HexBuffer = sha256HexBuffer;
exports.sha256HexString = sha256HexString;
exports.hash8Buffer = hash8Buffer;
exports.ensureTrailingSlash = ensureTrailingSlash;
exports.writeIfChangedBuffer = writeIfChangedBuffer;
exports.writeIfChangedString = writeIfChangedString;
exports.isAsciiLower = isAsciiLower;
exports.isAsciiUpper = isAsciiUpper;
exports.isAsciiDigit = isAsciiDigit;
exports.sanitizeFieldChars = sanitizeFieldChars;
exports.toRescriptFieldName = toRescriptFieldName;
exports.jsEntryExtensionSet = jsEntryExtensionSet;
exports.formatBunLogs = formatBunLogs;
exports.normalizeRootInput = normalizeRootInput;
exports.scanGlobPaths = scanGlobPaths;
exports.scanGlobPatternsUniqueSorted = scanGlobPatternsUniqueSorted;
exports.resolveProjectRoot = resolveProjectRoot;
exports.resolveClientSource = resolveClientSource;
exports.discoverManagedFiles = discoverManagedFiles;
exports.hasJsEntryExtension = hasJsEntryExtension;
exports.classifyAssetFiles = classifyAssetFiles;
exports.jsOutputRelativePath = jsOutputRelativePath;
exports.hashedRelativePath = hashedRelativePath;
exports.extractLogs = extractLogs;
exports.runBunBuild = runBunBuild;
exports.createRootRequire = createRootRequire;
exports.maybeTransformCssWithPostcss = maybeTransformCssWithPostcss;
exports.buildJavaScript = buildJavaScript;
exports.buildCss = buildCss;
exports.emitManagedAsset = emitManagedAsset;
exports.copyPublicFiles = copyPublicFiles;
exports.buildGeneratedJs = buildGeneratedJs;
exports.buildGeneratedRes = buildGeneratedRes;
exports.buildManifest = buildManifest;
exports.cleanOutputDirectory = cleanOutputDirectory;
exports.buildAssets = buildAssets;
exports.shouldTriggerSrcRebuild = shouldTriggerSrcRebuild;
exports.makeDebouncedTask = makeDebouncedTask;
exports.watchDirectory = watchDirectory;
exports.startDevWatch = startDevWatch;
exports.closeWatcher = closeWatcher;
exports.decodePathname = decodePathname;
exports.stripLeadingSlashes = stripLeadingSlashes;
exports.sanitizeUrlPath = sanitizeUrlPath;
exports.getServeRoots = getServeRoots;
exports.resolveServedFilePath = resolveServedFilePath;
exports.jsSourceCandidatesFromRequest = jsSourceCandidatesFromRequest;
exports.responseWithContentType = responseWithContentType;
exports.responseWithStatus = responseWithStatus;
exports.fileResponseFromPath = fileResponseFromPath;
exports.bufferToUtf8String = bufferToUtf8String;
exports.requestUrlPathname = requestUrlPathname;
exports.resolveDevManagedAssetResponse = resolveDevManagedAssetResponse;
exports.suspiciousRootNames = suspiciousRootNames;
exports.hasSuspiciousRoot = hasSuspiciousRoot;
exports.serveStaticFileFromBuild = serveStaticFileFromBuild;
/* devOutputDir Not a pure module */
