// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let AssetPipeline$ResX = require("./AssetPipeline.js");

let isDevelopment = process.env.NODE_ENV !== "production";

let startDevPromise = {
  contents: undefined
};

let startDevWatcher = {
  contents: undefined
};

let startedRoot = {
  contents: undefined
};

function closeWatcher() {
  let watcher = startDevWatcher.contents;
  if (watcher !== undefined) {
    AssetPipeline$ResX.closeWatcher(watcher);
    startDevWatcher.contents = undefined;
    return;
  }
}

async function startDev(root, param) {
  if (!isDevelopment) {
    return;
  }
  let resolvedRoot = await AssetPipeline$ResX.resolveProjectRoot(root);
  let existingPromise = startDevPromise.contents;
  if (existingPromise !== undefined) {
    let existingRoot = startedRoot.contents;
    if (existingRoot !== undefined && existingRoot !== resolvedRoot) {
      console.warn(`[resx] startDev() already initialized for ` + existingRoot + `; ignoring additional root ` + resolvedRoot);
    }
    return await existingPromise;
  }
  let startupPromise = (async () => {
    let watcher = await AssetPipeline$ResX.startDevWatch(resolvedRoot, true, error => {
      console.error(`[resx] dev asset rebuild failed\n` + String(error));
    });
    startDevWatcher.contents = watcher;
    try {
      await AssetPipeline$ResX.buildAssets(resolvedRoot, true, true);
    } catch (exn) {
      closeWatcher();
      throw exn;
    }
    startedRoot.contents = resolvedRoot;
  })();
  startDevPromise.contents = startupPromise;
  try {
    await startupPromise;
    return;
  } catch (exn) {
    startDevPromise.contents = undefined;
    startedRoot.contents = undefined;
    closeWatcher();
    throw exn;
  }
}

exports.startDev = startDev;
/* isDevelopment Not a pure module */
