// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var $$ReadableStream = {};

var BunFile = {};

var HeadersInit = {};

var $$Headers = {};

var $$URLSearchParams = {};

var $$Blob = {};

var $$Request = {};

var $$TextEncoder = {};

var Writer = {};

var $$WritableStream = {
  Writer: Writer
};

var Controller = {};

var $$TransformStream = {
  Controller: Controller
};

var $$Response = {};

var $$WebSocket = {};

var Server = {};

var $$URL = {};

var AsyncLocalStorage = {};

var Fs = {};

exports.$$ReadableStream = $$ReadableStream;
exports.BunFile = BunFile;
exports.HeadersInit = HeadersInit;
exports.$$Headers = $$Headers;
exports.$$URLSearchParams = $$URLSearchParams;
exports.$$Blob = $$Blob;
exports.$$Request = $$Request;
exports.$$TextEncoder = $$TextEncoder;
exports.$$WritableStream = $$WritableStream;
exports.$$TransformStream = $$TransformStream;
exports.$$Response = $$Response;
exports.$$WebSocket = $$WebSocket;
exports.Server = Server;
exports.$$URL = $$URL;
exports.AsyncLocalStorage = AsyncLocalStorage;
exports.Fs = Fs;
/* No side effect */
