// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let isDev = process.env.NODE_ENV !== "production";

function runDevServer(port) {
  Bun.serve({
    development: true,
    port: port + 1 | 0,
    fetch: async (request, server) => {
      if (server.upgrade(request)) {
        return undefined;
      } else {
        return new Response("", {
          status: 404
        });
      }
    },
    websocket: {
      open: _v => {}
    }
  });
}

function copy(search) {
  return new URLSearchParams(Object.fromEntries(search.entries()));
}

let URLSearchParams$1 = {
  copy: copy
};

exports.runDevServer = runDevServer;
exports.isDev = isDev;
exports.URLSearchParams = URLSearchParams$1;
/* isDev Not a pure module */
