// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let AssetPipeline$ResX = require("./AssetPipeline.js");
let Primitive_exceptions = require("@rescript/runtime/lib/js/Primitive_exceptions.js");

let UsageError = /* @__PURE__ */Primitive_exceptions.create("Cli-ResX.UsageError");

function printRootHelp() {
  console.log(`Usage: resx <command>

Commands:
  assets build     Build managed assets

Run \`resx assets build --help\` for command-specific options.`);
}

function printAssetsBuildHelp() {
  console.log(`Usage: resx assets build [options]

Options:
  --dev            Build dev assets into .resx/dev
  --watch          Watch for changes (requires --dev)
  --root <path>    Project root directory (default: current working directory)
  --clean          Clean output directory before build (default)
  --no-clean       Do not clean output directory before build
  -h, --help       Show this help`);
}

function parseAssetsBuildArgs(argv) {
  let options = {
    dev: false,
    watch: false,
    clean: true,
    root: undefined,
    help: false
  };
  let i = 0;
  while (i < argv.length) {
    let arg = argv[i];
    let exit = 0;
    switch (arg) {
      case "--clean" :
        let init = options;
        options = {
          dev: init.dev,
          watch: init.watch,
          clean: true,
          root: init.root,
          help: init.help
        };
        break;
      case "--dev" :
        let init$1 = options;
        options = {
          dev: true,
          watch: init$1.watch,
          clean: init$1.clean,
          root: init$1.root,
          help: init$1.help
        };
        break;
      case "--no-clean" :
        let init$2 = options;
        options = {
          dev: init$2.dev,
          watch: init$2.watch,
          clean: false,
          root: init$2.root,
          help: init$2.help
        };
        break;
      case "--root" :
        let nextIndex = i + 1 | 0;
        let value = argv[nextIndex];
        if (value !== undefined) {
          if (value.startsWith("--")) {
            throw {
              RE_EXN_ID: UsageError,
              _1: "Missing value for --root",
              Error: new Error()
            };
          }
          let init$3 = options;
          options = {
            dev: init$3.dev,
            watch: init$3.watch,
            clean: init$3.clean,
            root: value,
            help: init$3.help
          };
          i = nextIndex;
        } else {
          throw {
            RE_EXN_ID: UsageError,
            _1: "Missing value for --root",
            Error: new Error()
          };
        }
        break;
      case "--watch" :
        let init$4 = options;
        options = {
          dev: init$4.dev,
          watch: true,
          clean: init$4.clean,
          root: init$4.root,
          help: init$4.help
        };
        break;
      case "--help" :
      case "-h" :
        exit = 1;
        break;
      default:
        throw {
          RE_EXN_ID: UsageError,
          _1: `Unknown option: ` + arg,
          Error: new Error()
        };
    }
    if (exit === 1) {
      let init$5 = options;
      options = {
        dev: init$5.dev,
        watch: init$5.watch,
        clean: init$5.clean,
        root: init$5.root,
        help: true
      };
    }
    i = i + 1 | 0;
  };
  if (options.watch && !options.dev) {
    throw {
      RE_EXN_ID: UsageError,
      _1: "Invalid option combination: --watch requires --dev",
      Error: new Error()
    };
  }
  return options;
}

async function runAssetsBuild(parsed) {
  if (parsed.help) {
    console.log(`Usage: resx assets build [options]

Options:
  --dev            Build dev assets into .resx/dev
  --watch          Watch for changes (requires --dev)
  --root <path>    Project root directory (default: current working directory)
  --clean          Clean output directory before build (default)
  --no-clean       Do not clean output directory before build
  -h, --help       Show this help`);
    return {
      TAG: "ExitCode",
      _0: 0
    };
  }
  let root = parsed.root;
  if (parsed.watch) {
    let watcher = await AssetPipeline$ResX.startDevWatch(root, parsed.clean, error => {
      console.error(String(error));
    });
    try {
      await AssetPipeline$ResX.buildAssets(root, parsed.dev, parsed.clean);
    } catch (exn) {
      AssetPipeline$ResX.closeWatcher(watcher);
      throw exn;
    }
    process.on("SIGINT", () => {
      AssetPipeline$ResX.closeWatcher(watcher);
      process.exit(0);
    });
    process.on("SIGTERM", () => {
      AssetPipeline$ResX.closeWatcher(watcher);
      process.exit(0);
    });
    return "Watching";
  }
  await AssetPipeline$ResX.buildAssets(root, parsed.dev, parsed.clean);
  return {
    TAG: "ExitCode",
    _0: 0
  };
}

async function run(argv) {
  let command = argv[0];
  if (command !== undefined) {
    switch (command) {
      case "--help" :
      case "-h" :
        console.log(`Usage: resx <command>

Commands:
  assets build     Build managed assets

Run \`resx assets build --help\` for command-specific options.`);
        return {
          TAG: "ExitCode",
          _0: 0
        };
      case "assets" :
        let other = argv[1];
        if (other !== undefined) {
          switch (other) {
            case "--help" :
            case "-h" :
              console.log(`Usage: resx assets build [options]

Options:
  --dev            Build dev assets into .resx/dev
  --watch          Watch for changes (requires --dev)
  --root <path>    Project root directory (default: current working directory)
  --clean          Clean output directory before build (default)
  --no-clean       Do not clean output directory before build
  -h, --help       Show this help`);
              return {
                TAG: "ExitCode",
                _0: 0
              };
            case "build" :
              let parsed = parseAssetsBuildArgs(argv.slice(2));
              return await runAssetsBuild(parsed);
            default:
              throw {
                RE_EXN_ID: UsageError,
                _1: `Unknown assets subcommand: ` + other,
                Error: new Error()
              };
          }
        } else {
          console.log(`Usage: resx assets build [options]

Options:
  --dev            Build dev assets into .resx/dev
  --watch          Watch for changes (requires --dev)
  --root <path>    Project root directory (default: current working directory)
  --clean          Clean output directory before build (default)
  --no-clean       Do not clean output directory before build
  -h, --help       Show this help`);
          return {
            TAG: "ExitCode",
            _0: 0
          };
        }
      default:
        throw {
          RE_EXN_ID: UsageError,
          _1: `Unknown command: ` + command,
          Error: new Error()
        };
    }
  } else {
    console.log(`Usage: resx <command>

Commands:
  assets build     Build managed assets

Run \`resx assets build --help\` for command-specific options.`);
    return {
      TAG: "ExitCode",
      _0: 0
    };
  }
}

async function runFromArgv() {
  let argv = process.argv.slice(2);
  let code;
  try {
    code = await run(argv);
  } catch (raw_message) {
    let message = Primitive_exceptions.internalToException(raw_message);
    if (message.RE_EXN_ID === UsageError) {
      console.error(message._1);
      console.error("Run `resx assets build --help` for usage details.");
      return process.exit(2);
    } else if (message.RE_EXN_ID === "JsExn") {
      console.error(String(message._1));
      return process.exit(1);
    } else {
      console.error("Unknown error");
      return process.exit(1);
    }
  }
  if (typeof code !== "object") {
    return;
  } else {
    return process.exit(code._0);
  }
}

exports.UsageError = UsageError;
exports.printRootHelp = printRootHelp;
exports.printAssetsBuildHelp = printAssetsBuildHelp;
exports.parseAssetsBuildArgs = parseAssetsBuildArgs;
exports.runAssetsBuild = runAssetsBuild;
exports.run = run;
exports.runFromArgv = runFromArgv;
/* AssetPipeline-ResX Not a pure module */
