// Generated by ReScript, PLEASE EDIT WITH CARE


function make(actions) {
  return JSON.stringify(actions);
}

let Actions = {
  make: make
};

function make$1(config) {
  return JSON.stringify(config);
}

let ValidityMessage = {
  make: make$1
};

export {
  Actions ,
  ValidityMessage ,
}
/* No side effect */
