// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let CSRF$ResX = require("./CSRF.js");
let Hjsx$ResX = require("./Hjsx.js");

function CSRFToken(props) {
  return Hjsx$ResX.Elements.jsx("input", {
    name: CSRF$ResX.tokenInputName,
    type: "hidden",
    value: CSRF$ResX.generateToken()
  });
}

let make = CSRFToken;

exports.make = make;
/* CSRF-ResX Not a pure module */
