// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Hjsx$ResX = require("./Hjsx.js");
let HyperonsJs = require("./vendor/hyperons.js");

let context = HyperonsJs.createContext(undefined, "errorBoundary");

let make = context.Provider;

function ErrorBoundary(props) {
  return Hjsx$ResX.jsx(make, {
    value: props.renderError,
    children: props.children
  });
}

let make$1 = ErrorBoundary;

exports.make = make$1;
/* context Not a pure module */
