// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ResX__React = require("./ResX__React.js");
var HyperonsJs = require("./vendor/hyperons.js");

var context = HyperonsJs.createContext(undefined, "errorBoundary");

var make = context.Provider;

function ErrorBoundary(props) {
  return ResX__React.jsx(make, {
              value: props.renderError,
              children: props.children
            });
}

var make$1 = ErrorBoundary;

exports.make = make$1;
/* context Not a pure module */
