// Generated by ReScript, PLEASE EDIT WITH CARE

let Hjsx$ResX = require("./Hjsx.js");
let HyperonsJs = require("./vendor/hyperons.js");

let context = HyperonsJs.createContext(undefined, "errorBoundary");

let make = context.Provider;

function ErrorBoundary(props) {
  return Hjsx$ResX.jsx(make, {
    value: props.renderError,
    children: props.children
  });
}

let make$1 = ErrorBoundary;

export {
  make$1 as make,
}
/* context Not a pure module */
