// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$FormData = require("./FormData.js");

function expectCheckbox(t, name) {
  return $$FormData.expectCustom(t, name, (function (res) {
                if (!(res instanceof File) && typeof res !== "string" || !(typeof res === "string" && res === "on")) {
                  return {
                          TAG: "Ok",
                          _0: false
                        };
                } else {
                  return {
                          TAG: "Ok",
                          _0: true
                        };
                }
              }));
}

function expectDate(t, name) {
  return $$FormData.expectCustom(t, name, (function (res) {
                if (!(res instanceof File) && typeof res !== "string") {
                  return {
                          TAG: "Error",
                          _0: "Invalid date."
                        };
                }
                if (typeof res !== "string") {
                  return {
                          TAG: "Error",
                          _0: "Invalid date."
                        };
                }
                var date = new Date(res);
                if (isNaN(date.getTime())) {
                  return {
                          TAG: "Error",
                          _0: "Invalid date."
                        };
                } else {
                  return {
                          TAG: "Ok",
                          _0: date
                        };
                }
              }));
}

exports.expectCheckbox = expectCheckbox;
exports.expectDate = expectDate;
/* No side effect */
