// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let H$ResX = require("./H.js");
let CSRF$ResX = require("./CSRF.js");
let Stdlib_List = require("@rescript/runtime/lib/js/Stdlib_List.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let Belt_MapString = require("@rescript/runtime/lib/js/Belt_MapString.js");
let Primitive_option = require("@rescript/runtime/lib/js/Primitive_option.js");
let Nodeasync_hooks = require("node:async_hooks");
let HyperonsJs = require("./vendor/hyperons.js");
let RequestController$ResX = require("./RequestController.js");

function string(s) {
  return s;
}

function toEndpointURL(s) {
  return s;
}

let FormAction = {
  string: string,
  toEndpointURL: toEndpointURL
};

function getHtmxRouteKey(method, path) {
  return method + `:` + path;
}

function warnFormActionShadowsHtmxHandler(method, path) {
  console.warn(`[ResX.Handlers] Form action registration for ` + path + ` shadows an existing HTMX handler for ` + method + ` ` + path + `.`);
}

function warnIfFormActionShadowsHtmxHandler(state, path) {
  if (Belt_MapString.has(state.htmxHandlersByRoute, getHtmxRouteKey("GET", path))) {
    warnFormActionShadowsHtmxHandler("GET", path);
  }
  if (Belt_MapString.has(state.htmxHandlersByRoute, getHtmxRouteKey("POST", path))) {
    return warnFormActionShadowsHtmxHandler("POST", path);
  }
}

function warnIfHtmxHandlerIsShadowedByFormAction(state, method, path) {
  switch (method) {
    case "GET" :
    case "POST" :
      break;
    default:
      return;
  }
  if (Belt_MapString.has(state.formActionHandlersByPath, path)) {
    console.warn(`[ResX.Handlers] HTMX handler registration for ` + method + ` ` + path + ` is shadowed by an existing form action route on the same path.`);
    return;
  }
}

function registerFormActionHandler(state, registration) {
  if (Belt_MapString.has(state.formActionHandlersByPath, registration.path)) {
    let path = registration.path;
    console.warn(`[ResX.Handlers] Duplicate form action registration ignored for ` + path + `.`);
    return;
  } else {
    warnIfFormActionShadowsHtmxHandler(state, registration.path);
    state.formActionHandlersByPath = Belt_MapString.set(state.formActionHandlersByPath, registration.path, registration);
    return;
  }
}

function getTargetFormActionHandler(state, requestMethod, pathname) {
  switch (requestMethod) {
    case "GET" :
    case "POST" :
      return Belt_MapString.get(state.formActionHandlersByPath, pathname);
    default:
      return;
  }
}

function getTargetHtmxHandler(state, requestMethod, pathname) {
  return Belt_MapString.get(state.htmxHandlersByRoute, getHtmxRouteKey(requestMethod, pathname));
}

function isCsrfEnabledFor(state, m) {
  let v = state.defaultCsrfCheck;
  if (v.TAG === "ForAllMethods") {
    return v._0;
  }
  switch (m) {
    case "GET" :
      return Stdlib_Option.getOr(v.get, false);
    case "POST" :
      return Stdlib_Option.getOr(v.post, false);
    case "PUT" :
      return Stdlib_Option.getOr(v.put, false);
    case "DELETE" :
      return Stdlib_Option.getOr(v.delete, false);
    case "PATCH" :
      return Stdlib_Option.getOr(v.patch, false);
    default:
      return false;
  }
}

function defaultRenderTitle(segments) {
  return segments.join(" | ");
}

async function renderWithDocType(el, requestController, renderTitleOpt, onAfterRenderOpt) {
  let renderTitle = renderTitleOpt !== undefined ? renderTitleOpt : defaultRenderTitle;
  let onAfterRender = onAfterRenderOpt !== undefined ? onAfterRenderOpt : async () => {};
  let content = await H$ResX.renderToString(el);
  await onAfterRender();
  let appendToHead = await requestController.getAppendedHeadContent();
  let appendBeforeBodyEnd = await requestController.getAppendedBeforeBodyEndContent();
  let match = requestController.getTitleSegments();
  let appendToHead$1;
  if (match.length !== 0) {
    if (appendToHead !== undefined) {
      let titleElement = `<title>` + HyperonsJs.escapeString(renderTitle(match)) + `</title>`;
      appendToHead$1 = appendToHead + titleElement;
    } else {
      appendToHead$1 = `<title>` + HyperonsJs.escapeString(renderTitle(match)) + `</title>`;
    }
  } else {
    appendToHead$1 = appendToHead;
  }
  let content$1 = appendToHead$1 !== undefined ? content.replace("</head>", appendToHead$1 + "</head>") : content;
  let content$2 = appendBeforeBodyEnd !== undefined ? content$1.replace("</body>", appendBeforeBodyEnd + "</body>") : content$1;
  return requestController.getDocHeader() + content$2;
}

let defaultHeaders = [[
    "Content-Type",
    "text/html"
  ]];

async function handleRequestWithState(t, config) {
  let onAfterBuildResponse = config.onAfterBuildResponse;
  let onBeforeBuildResponse = config.onBeforeBuildResponse;
  let onBeforeSendResponse = config.onBeforeSendResponse;
  let render = config.render;
  let request = config.request;
  let stream = Stdlib_Option.getOr(config.experimental_stream, false);
  let url = new URL(request.url);
  let pathname = url.pathname;
  let targetFormActionHandler = getTargetFormActionHandler(t, request.method, pathname);
  let targetHtmxHandler = getTargetHtmxHandler(t, request.method, pathname);
  let ctx = await t.requestToContext(request);
  let requestController = RequestController$ResX.make();
  let setupHeaders = config.setupHeaders;
  let headers = setupHeaders !== undefined ? setupHeaders() : new Headers(defaultHeaders);
  let renderConfig_path = Stdlib_List.fromArray(pathname.split("/").filter(s => s.trim() !== ""));
  let renderConfig = {
    request: request,
    headers: headers,
    context: ctx,
    path: renderConfig_path,
    url: url,
    requestController: requestController
  };
  return await t.asyncLocalStorage.run(renderConfig, async _token => {
    let isFormAction = Stdlib_Option.isSome(targetFormActionHandler);
    let content;
    if (targetFormActionHandler !== undefined) {
      content = null;
    } else if (targetHtmxHandler !== undefined) {
      let csrfEnabled = Stdlib_Option.getOr(targetHtmxHandler.csrfCheckOpt, isCsrfEnabledFor(t, targetHtmxHandler.method));
      let csrfOk = csrfEnabled ? await CSRF$ResX.verifyRequest(request) : true;
      if (csrfOk) {
        content = await targetHtmxHandler.run({
          request: request,
          context: ctx,
          headers: headers,
          requestController: requestController
        });
      } else {
        requestController.setStatus(403);
        content = "Invalid CSRF token.";
      }
    } else {
      content = await render(renderConfig);
    }
    let responseType = targetFormActionHandler !== undefined ? "FormActionHandler" : (
        targetHtmxHandler !== undefined ? "HtmxHandler" : "Default"
      );
    if (onBeforeBuildResponse !== undefined) {
      await onBeforeBuildResponse({
        request: request,
        context: ctx,
        responseType: responseType,
        requestController: requestController
      });
    }
    if (isFormAction) {
      let reg = Stdlib_Option.getOrThrow(targetFormActionHandler, undefined);
      let csrfEnabled$1 = Stdlib_Option.getOr(reg.csrfCheckOpt, isCsrfEnabledFor(t, request.method));
      let csrfOk$1 = csrfEnabled$1 ? await CSRF$ResX.verifyRequest(request) : true;
      let response = csrfOk$1 ? await reg.run({
          request: request,
          context: ctx
        }) : new Response("Invalid CSRF token.", {
          status: 403
        });
      if (onBeforeSendResponse !== undefined) {
        return await onBeforeSendResponse({
          request: request,
          response: response,
          context: ctx,
          responseType: responseType
        });
      } else {
        return response;
      }
    }
    if (stream) {
      let match = new TransformStream({
        transform: (chunk, controller) => {
          controller.enqueue(chunk);
        }
      });
      let writer = match.writable.getWriter();
      let textEncoder = new TextEncoder();
      H$ResX.renderToStream(content, chunk => {
        let encoded = textEncoder.encode(chunk);
        writer.write(encoded);
      }).then(() => writer.close());
      let response$1 = new Response(match.readable, {
        status: 200,
        headers: [[
            "Content-Type",
            "text/html"
          ]]
      });
      if (onBeforeSendResponse !== undefined) {
        return await onBeforeSendResponse({
          request: request,
          response: response$1,
          context: ctx,
          responseType: responseType
        });
      } else {
        return response$1;
      }
    }
    let onAfterRender = onAfterBuildResponse !== undefined ? async () => await onAfterBuildResponse({
        request: request,
        context: ctx,
        responseType: responseType,
        requestController: requestController
      }) : undefined;
    let content$1 = await renderWithDocType(content, requestController, config.renderTitle, onAfterRender);
    let match$1 = requestController.getCurrentRedirect();
    let match$2 = requestController.getCurrentStatus();
    let response$2 = match$1 !== undefined ? Response.redirect(match$1[0], Primitive_option.toUndefined(match$1[1])) : new Response(content$1, {
        status: match$2,
        headers: Primitive_option.some(headers)
      });
    if (onBeforeSendResponse !== undefined) {
      return await onBeforeSendResponse({
        request: request,
        response: response$2,
        context: ctx,
        responseType: responseType
      });
    } else {
      return response$2;
    }
  });
}

function makeHtmxRunner(securityPolicy, handler) {
  return async param => {
    let requestController = param.requestController;
    let context = param.context;
    let request = param.request;
    let meta = await securityPolicy({
      request: request,
      context: context
    });
    if (meta.TAG === "Allow") {
      return await handler({
        request: request,
        context: context,
        headers: param.headers,
        requestController: requestController,
        securityPolicyData: meta._0
      });
    }
    requestController.setStatus(Stdlib_Option.getOr(meta.code, 403));
    return Stdlib_Option.getOr(meta.message, "Not Allowed.");
  };
}

function makeFormActionRunner(securityPolicy, handler) {
  return async param => {
    let context = param.context;
    let request = param.request;
    let meta = await securityPolicy({
      request: request,
      context: context
    });
    if (meta.TAG === "Allow") {
      return await handler({
        request: request,
        context: context,
        securityPolicyData: meta._0
      });
    } else {
      return new Response(Stdlib_Option.getOr(meta.message, "Not Allowed."), {
        status: Stdlib_Option.getOr(meta.code, 403)
      });
    }
  };
}

function registerHtmxPath(state, httpMethod, path, securityPolicy, handler, csrfCheck) {
  let run = makeHtmxRunner(securityPolicy, handler);
  let registration = {
    method: httpMethod,
    path: path,
    csrfCheckOpt: csrfCheck,
    run: run
  };
  let routeKey = getHtmxRouteKey(registration.method, registration.path);
  if (Belt_MapString.has(state.htmxHandlersByRoute, routeKey)) {
    let method = registration.method;
    let path$1 = registration.path;
    console.warn(`[ResX.Handlers] Duplicate HTMX handler registration ignored for ` + method + ` ` + path$1 + `.`);
    return;
  } else {
    warnIfHtmxHandlerIsShadowedByFormAction(state, registration.method, registration.path);
    state.htmxHandlersByRoute = Belt_MapString.set(state.htmxHandlersByRoute, routeKey, registration);
    return;
  }
}

function createHtmxRoute(state, httpMethod, path, securityPolicy, handler, csrfCheck) {
  let routePath = state.htmxApiPrefix + path;
  registerHtmxPath(state, httpMethod, routePath, securityPolicy, handler, csrfCheck);
  return routePath;
}

let defineHtmxRoute = registerHtmxPath;

function hxGetToEndpointURL(s) {
  return s;
}

function hxPostToEndpointURL(s) {
  return s;
}

function hxPutToEndpointURL(s) {
  return s;
}

function hxDeleteToEndpointURL(s) {
  return s;
}

function hxPatchToEndpointURL(s) {
  return s;
}

function make(requestToContext, options) {
  let state = {
    htmxHandlersByRoute: undefined,
    formActionHandlersByPath: undefined,
    requestToContext: requestToContext,
    asyncLocalStorage: new Nodeasync_hooks.AsyncLocalStorage(),
    htmxApiPrefix: Stdlib_Option.getOr(Stdlib_Option.flatMap(options, options => options.htmxApiPrefix), "/_api"),
    formActionHandlerApiPrefix: Stdlib_Option.getOr(Stdlib_Option.flatMap(options, options => options.formActionHandlerApiPrefix), "/_form"),
    defaultCsrfCheck: Stdlib_Option.getOr(Stdlib_Option.flatMap(options, options => options.defaultCsrfCheck), {
      TAG: "ForAllMethods",
      _0: false
    })
  };
  let useContext = () => state.asyncLocalStorage.getStore();
  let handleRequest = config => handleRequestWithState(state, config);
  return {
    useContext: useContext,
    handleRequest: handleRequest,
    formAction: (path, securityPolicy, handler, csrfCheck) => {
      let path$1 = state.formActionHandlerApiPrefix + path;
      let run = makeFormActionRunner(securityPolicy, handler);
      registerFormActionHandler(state, {
        path: path$1,
        csrfCheckOpt: csrfCheck,
        run: run
      });
      return path$1;
    },
    hxGet: (path, securityPolicy, handler, csrfCheck) => createHtmxRoute(state, "GET", path, securityPolicy, handler, csrfCheck),
    hxGetRef: path => state.htmxApiPrefix + path,
    hxGetDefine: (path, securityPolicy, handler, csrfCheck) => defineHtmxRoute(state, "GET", path, securityPolicy, handler, csrfCheck),
    hxPost: (path, securityPolicy, handler, csrfCheck) => createHtmxRoute(state, "POST", path, securityPolicy, handler, csrfCheck),
    hxPostRef: path => state.htmxApiPrefix + path,
    hxPostDefine: (path, securityPolicy, handler, csrfCheck) => defineHtmxRoute(state, "POST", path, securityPolicy, handler, csrfCheck),
    hxPut: (path, securityPolicy, handler, csrfCheck) => createHtmxRoute(state, "PUT", path, securityPolicy, handler, csrfCheck),
    hxPutRef: path => state.htmxApiPrefix + path,
    hxPutDefine: (path, securityPolicy, handler, csrfCheck) => defineHtmxRoute(state, "PUT", path, securityPolicy, handler, csrfCheck),
    hxDelete: (path, securityPolicy, handler, csrfCheck) => createHtmxRoute(state, "DELETE", path, securityPolicy, handler, csrfCheck),
    hxDeleteRef: path => state.htmxApiPrefix + path,
    hxDeleteDefine: (path, securityPolicy, handler, csrfCheck) => defineHtmxRoute(state, "DELETE", path, securityPolicy, handler, csrfCheck),
    hxPatch: (path, securityPolicy, handler, csrfCheck) => createHtmxRoute(state, "PATCH", path, securityPolicy, handler, csrfCheck),
    hxPatchRef: path => state.htmxApiPrefix + path,
    hxPatchDefine: (path, securityPolicy, handler, csrfCheck) => defineHtmxRoute(state, "PATCH", path, securityPolicy, handler, csrfCheck)
  };
}

function useContext(t) {
  return t.useContext();
}

function handleRequest(t, config) {
  return t.handleRequest(config);
}

function formAction(t, path, securityPolicy, handler, csrfCheck) {
  return t.formAction(path, securityPolicy, handler, csrfCheck);
}

function hxGet(t, path, securityPolicy, handler, csrfCheck) {
  return t.hxGet(path, securityPolicy, handler, csrfCheck);
}

function hxGetRef(t, path) {
  return t.hxGetRef(path);
}

function hxGetDefine(t, path, securityPolicy, handler, csrfCheck) {
  t.hxGetDefine(path, securityPolicy, handler, csrfCheck);
}

function hxPost(t, path, securityPolicy, handler, csrfCheck) {
  return t.hxPost(path, securityPolicy, handler, csrfCheck);
}

function hxPostRef(t, path) {
  return t.hxPostRef(path);
}

function hxPostDefine(t, path, securityPolicy, handler, csrfCheck) {
  t.hxPostDefine(path, securityPolicy, handler, csrfCheck);
}

function hxPut(t, path, securityPolicy, handler, csrfCheck) {
  return t.hxPut(path, securityPolicy, handler, csrfCheck);
}

function hxPutRef(t, path) {
  return t.hxPutRef(path);
}

function hxPutDefine(t, path, securityPolicy, handler, csrfCheck) {
  t.hxPutDefine(path, securityPolicy, handler, csrfCheck);
}

function hxDelete(t, path, securityPolicy, handler, csrfCheck) {
  return t.hxDelete(path, securityPolicy, handler, csrfCheck);
}

function hxDeleteRef(t, path) {
  return t.hxDeleteRef(path);
}

function hxDeleteDefine(t, path, securityPolicy, handler, csrfCheck) {
  t.hxDeleteDefine(path, securityPolicy, handler, csrfCheck);
}

function hxPatch(t, path, securityPolicy, handler, csrfCheck) {
  return t.hxPatch(path, securityPolicy, handler, csrfCheck);
}

function hxPatchRef(t, path) {
  return t.hxPatchRef(path);
}

function hxPatchDefine(t, path, securityPolicy, handler, csrfCheck) {
  t.hxPatchDefine(path, securityPolicy, handler, csrfCheck);
}

exports.FormAction = FormAction;
exports.make = make;
exports.formAction = formAction;
exports.hxGet = hxGet;
exports.hxGetRef = hxGetRef;
exports.hxGetDefine = hxGetDefine;
exports.hxGetToEndpointURL = hxGetToEndpointURL;
exports.hxPost = hxPost;
exports.hxPostRef = hxPostRef;
exports.hxPostDefine = hxPostDefine;
exports.hxPostToEndpointURL = hxPostToEndpointURL;
exports.hxPut = hxPut;
exports.hxPutRef = hxPutRef;
exports.hxPutDefine = hxPutDefine;
exports.hxPutToEndpointURL = hxPutToEndpointURL;
exports.hxDelete = hxDelete;
exports.hxDeleteRef = hxDeleteRef;
exports.hxDeleteDefine = hxDeleteDefine;
exports.hxDeleteToEndpointURL = hxDeleteToEndpointURL;
exports.hxPatch = hxPatch;
exports.hxPatchRef = hxPatchRef;
exports.hxPatchDefine = hxPatchDefine;
exports.hxPatchToEndpointURL = hxPatchToEndpointURL;
exports.useContext = useContext;
exports.handleRequest = handleRequest;
/* H-ResX Not a pure module */
