// Generated by ReScript, PLEASE EDIT WITH CARE

let HyperonsJs = require("./vendor/hyperons.js");

let jsxFragment = HyperonsJs.Fragment;

function dangerouslyOutputUnescapedContent(prim) {
  return HyperonsJs.createRaw(prim);
}

function jsx(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

function jsxs(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

function jsx$1(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

function jsxs$1(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

let Elements = {
  jsx: jsx$1,
  jsxs: jsxs$1
};

export {
  jsxFragment ,
  dangerouslyOutputUnescapedContent ,
  jsx ,
  jsxs ,
  Elements ,
}
/* jsxFragment Not a pure module */
