// Generated by ReScript, PLEASE EDIT WITH CARE

let RequestController$ResX = require("./RequestController.js");

function RenderBeforeBodyEnd(props) {
  RequestController$ResX.appendBeforeBodyEnd(props.requestController, props.children);
  return null;
}

let make = RenderBeforeBodyEnd;

export {
  make ,
}
/* RequestController-ResX Not a pure module */
