// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let RequestController$ResX = require("./RequestController.js");

function RenderBeforeBodyEnd(props) {
  RequestController$ResX.appendBeforeBodyEnd(props.requestController, props.children);
  return null;
}

let make = RenderBeforeBodyEnd;

exports.make = make;
/* RequestController-ResX Not a pure module */
