// Generated by ReScript, PLEASE EDIT WITH CARE

let RequestController$ResX = require("./RequestController.js");

function RenderInHead(props) {
  RequestController$ResX.appendToHead(props.requestController, props.children);
  return null;
}

let make = RenderInHead;

export {
  make ,
}
/* RequestController-ResX Not a pure module */
