// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function RenderInHead(props) {
  props.requestController.appendToHead(props.children);
  return null;
}

let make = RenderInHead;

exports.make = make;
/* No side effect */
