// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var RequestController$ResX = require("./RequestController.js");

function RenderInHead(props) {
  RequestController$ResX.appendToHead(props.requestController, props.children);
  return null;
}

var make = RenderInHead;

exports.make = make;
/* RequestController-ResX Not a pure module */
