// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let H$ResX = require("./H.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");

function make() {
  let state = {
    status: 200,
    redirect: undefined,
    docHeader: "<!DOCTYPE html>",
    headContent: [],
    bodyEndContent: [],
    titleSegments: []
  };
  return {
    setStatus: status => {
      state.status = status;
    },
    redirect: (url, status) => {
      state.redirect = [
        url,
        status
      ];
      return null;
    },
    getCurrentStatus: () => state.status,
    getCurrentRedirect: () => state.redirect,
    getTitleSegments: () => state.titleSegments.slice(),
    getDocHeader: () => Stdlib_Option.getOr(state.docHeader, ""),
    setDocHeader: docHeader => {
      state.docHeader = docHeader;
    },
    appendToHead: content => {
      state.headContent.push(content);
    },
    getAppendedHeadContent: async () => {
      let headContent = state.headContent;
      if (headContent.length !== 0) {
        return await H$ResX.renderToString(headContent);
      }
    },
    appendBeforeBodyEnd: content => {
      state.bodyEndContent.push(content);
    },
    getAppendedBeforeBodyEndContent: async () => {
      let bodyEndContent = state.bodyEndContent;
      if (bodyEndContent.length !== 0) {
        return await H$ResX.renderToString(bodyEndContent);
      }
    },
    appendTitleSegment: segment => {
      state.titleSegments.push(segment);
    },
    prependTitleSegment: segment => {
      state.titleSegments.unshift(segment);
    },
    setFullTitle: title => {
      state.titleSegments.splice(0, state.titleSegments.length, title);
    }
  };
}

function setStatus(t, status) {
  t.setStatus(status);
}

function redirect(t, url, status) {
  return t.redirect(url, status);
}

function getCurrentStatus(t) {
  return t.getCurrentStatus();
}

function getCurrentRedirect(t) {
  return t.getCurrentRedirect();
}

function getTitleSegments(t) {
  return t.getTitleSegments();
}

function getDocHeader(t) {
  return t.getDocHeader();
}

function setDocHeader(t, docHeader) {
  t.setDocHeader(docHeader);
}

function appendToHead(t, content) {
  t.appendToHead(content);
}

function getAppendedHeadContent(t) {
  return t.getAppendedHeadContent();
}

function appendBeforeBodyEnd(t, content) {
  t.appendBeforeBodyEnd(content);
}

function getAppendedBeforeBodyEndContent(t) {
  return t.getAppendedBeforeBodyEndContent();
}

function appendTitleSegment(t, segment) {
  t.appendTitleSegment(segment);
}

function prependTitleSegment(t, segment) {
  t.prependTitleSegment(segment);
}

function setFullTitle(t, title) {
  t.setFullTitle(title);
}

exports.make = make;
exports.setStatus = setStatus;
exports.redirect = redirect;
exports.getCurrentStatus = getCurrentStatus;
exports.getCurrentRedirect = getCurrentRedirect;
exports.getTitleSegments = getTitleSegments;
exports.getDocHeader = getDocHeader;
exports.appendToHead = appendToHead;
exports.getAppendedHeadContent = getAppendedHeadContent;
exports.appendBeforeBodyEnd = appendBeforeBodyEnd;
exports.getAppendedBeforeBodyEndContent = getAppendedBeforeBodyEndContent;
exports.appendTitleSegment = appendTitleSegment;
exports.prependTitleSegment = prependTitleSegment;
exports.setFullTitle = setFullTitle;
exports.setDocHeader = setDocHeader;
/* H-ResX Not a pure module */
