// Generated by ReScript, PLEASE EDIT WITH CARE

let H$ResX = require("./H.js");
let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");

function make() {
  return {
    status: 200,
    redirect: undefined,
    docHeader: "<!DOCTYPE html>",
    headContent: [],
    bodyEndContent: [],
    titleSegments: []
  };
}

function setStatus(t, status) {
  t.status = status;
}

function redirect(t, url, status) {
  t.redirect = [
    url,
    status
  ];
  return null;
}

function getCurrentStatus(t) {
  return t.status;
}

function getCurrentRedirect(t) {
  return t.redirect;
}

function getTitleSegments(t) {
  return t.titleSegments.slice();
}

function getDocHeader(t) {
  return Stdlib_Option.getOr(t.docHeader, "");
}

function setDocHeader(t, docHeader) {
  t.docHeader = docHeader;
}

function appendToHead(t, content) {
  t.headContent.push(content);
}

function appendBeforeBodyEnd(t, content) {
  t.bodyEndContent.push(content);
}

function appendTitleSegment(t, segment) {
  t.titleSegments.push(segment);
}

function prependTitleSegment(t, segment) {
  t.titleSegments.unshift(segment);
}

function setFullTitle(t, title) {
  t.titleSegments.splice(0, t.titleSegments.length, title);
}

async function getAppendedHeadContent(t) {
  let headContent = t.headContent;
  if (headContent.length !== 0) {
    return await H$ResX.renderToString(headContent);
  }
}

async function getAppendedBeforeBodyEndContent(t) {
  let bodyEndContent = t.bodyEndContent;
  if (bodyEndContent.length !== 0) {
    return await H$ResX.renderToString(bodyEndContent);
  }
}

export {
  make ,
  setStatus ,
  redirect ,
  getCurrentStatus ,
  getCurrentRedirect ,
  getTitleSegments ,
  getDocHeader ,
  appendToHead ,
  getAppendedHeadContent ,
  appendBeforeBodyEnd ,
  getAppendedBeforeBodyEndContent ,
  appendTitleSegment ,
  prependTitleSegment ,
  setFullTitle ,
  setDocHeader ,
}
/* H-ResX Not a pure module */
