// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


((function () {
        var getTarget = function (target, $$this) {
          if (typeof target !== "object") {
            return $$this;
          } else {
            return document.querySelector(target.selector);
          }
        };
        var handleAction = function (action, $$this) {
          var target;
          target = action.kind === "CopyToClipboard" ? null : getTarget(action.target, $$this);
          if (target === null) {
            if (action.kind !== "CopyToClipboard") {
              return ;
            }
            var onAfterFailure = action.onAfterFailure;
            var onAfterSuccess = action.onAfterSuccess;
            navigator.clipboard.writeText(action.text).catch(function (param) {
                    if (onAfterFailure !== undefined) {
                      return Promise.resolve((onAfterFailure.forEach(function (action) {
                                        handleAction(action, $$this);
                                      }), undefined));
                    } else {
                      return Promise.resolve();
                    }
                  }).then(function () {
                  if (onAfterSuccess !== undefined) {
                    onAfterSuccess.forEach(function (action) {
                          handleAction(action, $$this);
                        });
                    return ;
                  }
                  
                });
            return ;
          }
          switch (action.kind) {
            case "ToggleClass" :
                action.className.split(" ").forEach(function (className) {
                      target.classList.toggle(className);
                    });
                return ;
            case "RemoveClass" :
                action.className.split(" ").forEach(function (className) {
                      target.classList.remove(className);
                    });
                return ;
            case "AddClass" :
                action.className.split(" ").forEach(function (className) {
                      target.classList.add(className);
                    });
                return ;
            case "SwapClass" :
                action.fromClassName.split(" ").forEach(function (className) {
                      target.classList.remove(className);
                    });
                action.toClassName.split(" ").forEach(function (className) {
                      target.classList.add(className);
                    });
                return ;
            case "RemoveElement" :
                return target.remove();
            case "CopyToClipboard" :
                return ;
            
          }
        };
        document.addEventListener("click", (function ($$event) {
                var $$this = $$event.target;
                var match = $$this.attributes["resx-onclick"];
                var actions = match !== undefined ? JSON.parse(match.value) : [];
                actions.forEach(function (action) {
                      handleAction(action, $$this);
                    });
              }));
        document.addEventListener("invalid", (function ($$event) {
                var $$this = $$event.target;
                var match = $$this.validity;
                var match$1 = $$this.attributes["resx-validity-message"];
                if (match === undefined) {
                  return ;
                }
                if (match.valid) {
                  return ;
                }
                if (match$1 === undefined) {
                  return ;
                }
                var validityMessages = JSON.parse(match$1.value);
                var messageToSet = match.badInput ? validityMessages.badInput : (
                    match.patternMismatch ? validityMessages.patternMismatch : (
                        match.rangeOverflow ? validityMessages.rangeOverflow : (
                            match.rangeUnderflow ? validityMessages.rangeUnderflow : (
                                match.stepMismatch ? validityMessages.stepMismatch : (
                                    match.tooLong ? validityMessages.tooLong : (
                                        match.tooShort ? validityMessages.tooShort : (
                                            match.typeMismatch ? validityMessages.typeMismatch : (
                                                match.valueMissing ? validityMessages.valueMissing : undefined
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  );
                if (messageToSet !== undefined) {
                  return $$this.setCustomValidity(messageToSet);
                }
                
              }), true);
        document.addEventListener("change", (function ($$event) {
                var $$this = $$event.target;
                var match = $$this.attributes["resx-validity-message"];
                if (match !== undefined) {
                  return $$this.setCustomValidity("");
                }
                
              }));
      })());

/*  Not a pure module */
