// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var HyperonsJs = require("./vendor/hyperons.js");

function jsxs(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

var jsxFragment = HyperonsJs.Fragment;

function jsx(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

exports.jsxs = jsxs;
exports.jsxFragment = jsxFragment;
exports.jsx = jsx;
/* jsxFragment Not a pure module */
