// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(actions) {
  return JSON.stringify(actions);
}

var Actions = {
  make: make
};

function make$1(config) {
  return JSON.stringify(config);
}

var ValidityMessage = {
  make: make$1
};

exports.Actions = Actions;
exports.ValidityMessage = ValidityMessage;
/* No side effect */
