// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var HyperonsJs = require("./vendor/hyperons.js");

var jsxFragment = HyperonsJs.Fragment;

function jsx(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

function jsxs(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

function jsx$1(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

function jsxs$1(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

var DOM = {
  jsx: jsx$1,
  jsxs: jsxs$1
};

exports.jsxFragment = jsxFragment;
exports.jsx = jsx;
exports.jsxs = jsxs;
exports.DOM = DOM;
/* jsxFragment Not a pure module */
