// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var HyperonsJs = require("./vendor/hyperons.js");

function jsx(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

function jsxs(prim0, prim1) {
  return HyperonsJs.h(prim0, prim1);
}

exports.jsx = jsx;
exports.jsxs = jsxs;
/* ./vendor/hyperons.js Not a pure module */
